### ISSUE TITLE
Choosing output directory path for generated files 

### ISSUE THREAD

**Issue by Aristidios** [heftapp/graphql_codegen#102]
**Motivation :**

- Generating files with graphql_codegen is easy & great as it finds where is located our `schema.graphql` without having to indicate it

What is less great is that all the **generated `Dart` files** get mixed up with our "original" `.graphql` files

**Solution :**

  It would be nicer if the generated Dart files -> were generated in a sub-folder named `gen` or `generated_graphql` 

_Or being able to choose the output directory_

**Comment by budde377** [comment]
Released as `v0.10.0-beta.3`. Check the README for more info!
