### ISSUE TITLE
[Question] How to mock QueryResult for unit test ?

### ISSUE THREAD

**Issue by Kiruel** [heftapp/graphql_codegen#113]
Hi and thanks for the package !

I making some unit test for the graphql client and I would like to know how to mock the QueryResult when perform a query method. Let me explain why I'm block on this:

My test:
```dart
    test(
      'should checkEmailVerified',
      () async {
        // arrange
        when(() => graphqlClient.queryGetEmailVerified())
            .thenAnswer((_) async => {}); // HERE the return should be a `QueryResult<QueryGetEmailVerified>`
        // act
        final result = await datasource.checkEmailVerified();

        // assert
      },
    );
```

The source code:
```dart
  @override
  Future<bool> checkEmailVerified() async {
    try {
      final result = await graphQLClient.queryGetEmailVerified();
      if (result.parsedData != null) {
          return Future.value(result.parsedData?.me.emailVerified);
      }
  }
```
I can't find any good example to create the class mock to send to the `thenAnswer`. Can someone help me on that ?
I want to change the response data for example.

I can't do that for example, because the BaseOptions is private:
```dart
final tResult = QueryResult<QueryGetEmailVerified>(
          source: QueryResultSource.network,
          options: BaseOptions<QueryGetEmailVerified>() // HERE fail because private
        );
```

**Comment by budde377** [comment]
I think you need to mock the link. Take a look at how we test the underlying client https://github.com/zino-hofmann/graphql-flutter/blob/main/packages/graphql/test/graphql_client_test.dart

**Comment by Kiruel** [comment]
But here https://github.com/zino-hofmann/graphql-flutter/blob/main/packages/graphql/test/graphql_client_test.dart#L128

It's more for a basic query without the generated method. 

For my method I need to pass a `OptionsQueryGetEmailVerified?` (the option generated by the lib). I don't think I can do the same of mock the link etc...

Btw if I resolve this I will probably make an example mock test for this. Could be really useful for others.

**Comment by budde377** [comment]
Amazing! Thanks for sharing your solution.
