### ISSUE TITLE
Use Freezed with unions

### ISSUE THREAD

**Issue by Noteofman** [heftapp/graphql_codegen#114]
I know it would be a big chunk of work, but are there any thoughts about integrating freezed when dealing with unions, allowing the interface to be more exhaustive.

**Comment by budde377** [comment]
Thanks for creating this issue. Can you please elaborate on what you mean? What kind of integration are you looking for and how would this improve?

**Comment by Kiruel** [comment]
I think he is talking about this problem:

A way to allow $ in class when freeze generate class in [unions](https://pub.dev/packages/freezed#union-types-and-sealed-classes). So I got class model like this `Mutation$GetUserToken` with a $. But when I try to use freezed like this:
```dart
@Freezed(makeCollectionsUnmodifiable: false)
class Success with _$Success {
  const factory Success.refreshToken(
      Mutation$GetUserToken token) = RefreshTokenSuccess;
}
```
Freeze generate this:
```dart
required TResult Function(GetUserToken token) refreshSendBirdToken,
```
Without the $.
It should be:
```dart
required TResult Function(Mutation$GetUserSendBirdToken token) refreshSendBirdToken,
```

So I don't know if the modification should be from freezed or from this package.

**Comment by budde377** [comment]
Cheers, check out this comment https://github.com/heftapp/graphql_codegen/issues/82#issuecomment-1144783054
