### ISSUE TITLE
Unable to compile for windows

### ISSUE THREAD

**Issue by FireAndIceFrog** [heftapp/graphql_codegen#115]
Hi there!

Im trying to compare artemis with this package however when I tried to run with my own graphQL schema Ive noticed that the generated files have the wrong import for their json_serializeable counterparts.

For example:

![image](https://user-images.githubusercontent.com/60675668/178408191-a32debb4-0349-435f-b5c6-9acbb72bbc48.png)

The error generated basically says that the part directive should be the file name alone with no reference to the containing folder.

I know its a problem with the `outputDirectory` option because it can alter the import directive.

Note: when the outputDirectory isnt set it creates an even worse import:

![image](https://user-images.githubusercontent.com/60675668/178408724-7268c714-426f-4a75-9ee0-f4698c2f1cc7.png)

I dont know your package well but basically the fix would be to remove all folders/to/this/file in the part directive and let json_serializeable do its thing.

### Current Behaviour
bad imports seen above, compiled on windows

### Expected behaviour
Import should be simply the file name

part "lib/./example.graphql.g.dart" -> part "example.graphql.g.dart"

**Comment by budde377** [comment]
Thanks for reporting this! How does it look when you have generated files importing other generated files. E.g.,

```graphql
# schema.graphql

type Query { 
  foo: Enum
}

enum Enum { ONE TWO THREE }

```

and 


```graphql
# query.graphql

query Q {
  foo 
}

```

**Comment by budde377** [comment]
Please try out version `0.10.0-beta.5` to see if it fixes the problem.

**Comment by FireAndIceFrog** [comment]
Yep! It works now thanks :) When will this be released?

The code importing seems to work fine with files in different folders, its all compiled nicely.
