### ISSUE TITLE
Feature Request: Make output dir relative to project root

### ISSUE THREAD

**Issue by FireAndIceFrog** [heftapp/graphql_codegen#117]
Id like to have nested folders
graphql
 - queries
     - authentication
          - login.graphql
 - schema.graphql 

With the current method, the folders dont marry up.

With an output folder of ../lib/generated_models a folder is generated in the graphql folder instead of its correct placement of the lib/generated_models

This limits the ability to create folders for this tool.

# Expected Behaviour
Make folder resolution relative to the package itself, not each graphql file.

**Comment by budde377** [comment]
Interesting suggestion. Can you please outline how you'd expect a more complex example to work? Say, having multiple graphql files with the same name spread around the project.

**Comment by FireAndIceFrog** [comment]
Since you already have an `assetsPath` arguement, the assumption would be that all graphql files/containing folders are stored within the root `assetsPath` directory.

Path resolving would then replace the ```assetsPath``` directory with the `outputDir` path.

Im Assuming you can already handle files with the same name

# Build.yaml
-----------------------------
 Assets path: "graphQl/**.graphql"
 outputDir: "lib/models" <-- notice that the lib is an absolute path type
 
# Example
## GraphQL
graphQL/schema.graphql
graphQL/query.graphql
graphQl/MyApi/query.graphql
--------------------------------------
## Output
lib/models/query.graphql.dart
lib/models/MyApi/query.graphql.dart
