### ISSUE TITLE
Merge Query types defined in different `.graphql` files?

### ISSUE THREAD

**Issue by crizant-mpower** [heftapp/graphql_codegen#120]
Hi, I have dozens of `*.graphql` file that contains schema.
Is it possible to define a "schema directory" in `build.yaml` so that it imports all `*.graphql` files and use them as schema?

**Comment by budde377** [comment]
The generator shouldn't care if your schema is split in multiple files or is in one. What problems are you facing with your current setup?

**Comment by crizant-mpower** [comment]
Here is the simplified scenario,
I defined the following schema in `user.graphql`:
```
type User {
  id: ID!
  name: String!
}
```

Then in `query.graphql`:
```
query User($userId: ID!) {
  user(id: $userId) {
    id,
    name,
  }
}
```

The builder gives the following error:
```
Invalid GraphQL: Failed to find type for field user on Query
```

But I renamed `user.graphql` to `schema.graphql`, the issue is gone.

**Comment by budde377** [comment]
That's strange. It isn't looking for any file named schema, which is something we test for. Can you give me some more info on the file structure you have and your build config?

**Comment by crizant-mpower** [comment]
I'm able to reproduce the issue by three files:
```
# user.graphql
type User {
  id: ID!
  name: String!
}

type Query {
  user(id: ID!): User
}

```

```
# task.graphql
type Task {
  id: ID!
  name: String!
}

type Query {
  task(id: ID!): Task
}
```

```
query User($userId: ID!) {
  user(id: $userId) {
    id
    name
  }
}
```

It seems the `type Query` are conflicting with each other.

**Comment by crizant-mpower** [comment]
I'm new to graphql, but the same `.graphql` files have been used in javascript projects for some time and have no issue at all.
Is it possible for this generator to support this style as well?

**Comment by budde377** [comment]
Everything is possible, but before we go ahead and accommodate invalid graphql. Can you tell me a bit more about your use case. Normally I'd expect the schema to be defined on the backend which would remove the need for you to specify it at all. How does this work in your use case?

**Comment by crizant-mpower** [comment]
Btw I found that there's an `extend` keyword in graphql spec, maybe we could work in this way.

**Comment by budde377** [comment]
For now, the recommended approach is to generate valid schemas, preferably fetching them from your API.
