### ISSUE TITLE
Undefined Class & Undefined Method

### ISSUE THREAD

**Issue by tsrCodes** [heftapp/graphql_codegen#13]
```
Undefined class 'GQLOptionsQueryposts'.
Try changing the name to the name of an existing class, or creating a class with the name 'GQLOptionsQueryposts'.

The method 'GQLOptionsQueryposts' isn't defined for the type 'GQLFQueryposts'.
Try correcting the name to the name of an existing method, or defining a method named 'GQLOptionsQueryposts'.
```

Any Help !! Not Sure What it is : (

**Comment by budde377** [comment]
Hi @tsrCodes, can you please add a bit more context? If you'd include your queries and code snippets that'd be a huge help!

**Comment by tsrCodes** [comment]
Here my Query

```graphql
query jobs($first: Int, $endCursor: String) {
  jobs(first: $first, after: $endCursor) {
    pageInfo {
      hasNextPage
      endCursor
    }
    nodes {
      ...Details
    }
  }
}
```

then run the  below command 
```
flutter pub run build_runner build
```

gives the `posts.graphql.dart` & `posts.graphql.g.dart`.

the error comes on `posts.graphql.dart` file

**Comment by budde377** [comment]
Cheers, can you link the generated code and your schema as well? I'm trying to construct a reproducible example

**Comment by budde377** [comment]
Actually, can you share your configuration file? If you're using the graphql_flutter client, you'll also need to add the graphql_client client

**Comment by tsrCodes** [comment]
`build.yaml` right ?

here's mine

```yaml
targets:
  $default:
    builders:
      graphql_codegen:
        options:
          clients:
            - graphql_flutter
```

**Comment by budde377** [comment]
Awesome, try and add graphql_client as a client as well.

**Comment by tsrCodes** [comment]
Oops My Bad !! Not Adding graphql client !!! Sorry

**Comment by tsrCodes** [comment]
Can You Update all dependencies to Latest versions

**Comment by budde377** [comment]
All dependencies are updated on `0.5.0-alpha.0`
