### ISSUE TITLE
Feature Request: Lint ignore (or fix)

### ISSUE THREAD

**Issue by baconcheese113** [heftapp/graphql_codegen#141]
My small-ish app currently has 3,759 flutter lint "hints" in the Dart Analyzer tool, and I think they're all from the generated graphql_codegen dart files.

Some examples:
`Annotate overridden members`
![image](https://user-images.githubusercontent.com/1386713/180601319-d28c3d7b-8941-4e19-a9f4-aa9b9b069d4d.png)
`Prefer is! operator`
![image](https://user-images.githubusercontent.com/1386713/180601330-fe28e009-305e-4d69-b953-f290043d38f4.png)
`Private field could be final`
![image](https://user-images.githubusercontent.com/1386713/180601367-828f96fc-a142-4755-b8e9-4312fe0c075b.png)

Not sure if there's much of a performance hit for the linter checking through all these generated files, but is there a way they could be generated with 
```dart
// ignore_for_file: type=lint
```
Since nobody should be fixing lint errors in them

Artemis has something similar [ignore_for_file](https://github.com/comigor/artemis#configuration) but I'm not sure what the benefit is of linting generated files at all unless you're working on the generator

**Comment by budde377** [comment]
You can add this in the `generatedFileHeader` option

**Comment by baconcheese113** [comment]
Ahhh, perfect, I'll thought that was for something different, I'll update the docs

**Comment by baconcheese113** [comment]
Okay, that worked for the `graphql.dart` files but not the `graphql.g.dart` files
![image](https://user-images.githubusercontent.com/1386713/180624250-12b573b8-89d7-4781-a2ac-89422417cb47.png)

**Comment by budde377** [comment]
For that it might be easier just to exclude the files: https://dart.dev/guides/language/analysis-options#excluding-files

**Comment by budde377** [comment]
I don't think generated files need to pass lints instead users should ignore the files.
