### ISSUE TITLE
Support @OneOf

### ISSUE THREAD

**Issue by ehsanonline** [heftapp/graphql_codegen#143]
for the client side, I think it only need to ignore other fields completely instead of passing them with null value, so it should be that hard.
```graphql
input userInput {
  byID: ID
  byEmail: String
}
```
for example when I use `byID`, I got an error that says `OneOf input objects require have exacly one field` . so I think it passes `byEmail` with `null` value, but it has to removed completely.
[RFC](https://github.com/graphql/graphql-spec/pull/825)

**Comment by budde377** [comment]
Check [here](https://github.com/heftapp/graphql_codegen/issues/54#issuecomment-1091870570), [here](https://github.com/heftapp/graphql_codegen/issues/103), and the option [here](https://github.com/heftapp/graphql_codegen/tree/main/packages/graphql_codegen#strip-null-from-input-serializers).

**Comment by ehsanonline** [comment]
Thanks! can we have that for just some inputs?

**Comment by budde377** [comment]
Yes you may

**Comment by budde377** [comment]
In the lastest version `0.11.0-beta.1` we've removed the dependency to `json_serializable` which allows us to write the following

```graphql

input I {
  s: String
  b: Boolean
}

```

```dart
Input$I(s: 'Foobar').toJson(); // {"s": "Foobar", "b": null}
Input$I.withoutNulls(s: 'Foobar').toJson(); // {"s": "Foobar"}

```
