### ISSUE TITLE
Remove warning messages in generated code

### ISSUE THREAD

**Issue by mwawrusch** [heftapp/graphql_codegen#154]
I get about 600 warnings in my generated code for

Name non-constant identifiers using lowerCamelCase. Please add an ignore statement (either at the file level or individual line level), or if the warning is actually reasonable, remove the cause of the warning.

BTW, great library, love it.

```
@JsonSerializable(explicitToJson: true)
class Mutation$AuthExchangeMagic {
  Mutation$AuthExchangeMagic(
      // ignore: non_constant_identifier_names
      {required this.authExchangeMagic, required this.$__typename});
```

**Comment by budde377** [comment]
Thanks for reaching out. The recommended approach is to either add a custom file header or ignore the generated files from your linter (see https://github.com/heftapp/graphql_codegen/tree/main/packages/graphql_codegen#generated-file-headers).
