### ISSUE TITLE
Generated files still referencing `graphql.g.dart`

### ISSUE THREAD

**Issue by baconcheese113** [heftapp/graphql_codegen#155]
After updating from `0.10.0-beta.7` to `0.10.3` and attempting to generate the types I get errors from `schema.graphql.dart` because it still generates with the following line:
```dart
// lib/graphql/__generated__/schema.graphql.dart
import 'package:json_annotation/json_annotation.dart';
part 'schema.graphql.g.dart';
```

I also get errors for most of the Input Json transformers
```dart
factory Input$CapsulesFind.fromJson(Map<String, dynamic> json) =>
      _$Input$CapsulesFindFromJson(json);
```
Error is 
`The method '_$Input$CapsulesFindFromJson' isn't defined for the type 'Input$CapsulesFind'. (Documentation)  Try correcting the name to the name of an existing method, or defining a method named '_$Input$CapsulesFindFromJson'.`

You can reproduce with my [graphql_codegen example project](https://github.com/baconcheese113/graphql_codegen_example)

**Comment by budde377** [comment]
Thanks for reporting this, I tried to pull your repo and upgrade the dependency to `0.10.3` and it seems to work for me. Have you tried to run the build command with `--delete-conflicting-outputs`? Are there any build errors?  You can also try out the latest version `0.11.0-beta.2` which removes the `json_serializable` dependency completely.

**Comment by baconcheese113** [comment]
Works fine with `0.11.0-beta.4`, not sure what happened 👍
