### ISSUE TITLE
Fragment on <interface> not working

### ISSUE THREAD

**Issue by Sander0542** [heftapp/graphql_codegen#158]
When I am using a fragment which implements on an interface, the query doesn't get generated with that part

```graphql
interface IUser {
    id: ID!
}

type User implements IUser {
    id: ID!
}

type Location {
    id: ID!

    users: [User!]!
}

type Query {
    locations: [Location!]!
}

fragment UserSummary on IUser {
    id
}

fragment LocationWithUsers on Location {
    id
    users {
        ...UserSummary
    }
}

query GetLocations {
    locations {
        ...LocationWithUsers
    }
}
```

**Comment by budde377** [comment]
Thanks for reporting this. I haven't been able to reproduce your issue (please take a look at the referenced PR). You do seem to have an error in your fragment as well:

```graphql
fragment PersonSummary on IPerson {
  id: ID!
}
```

should probably be 

```graphql
fragment PersonSummary on IPerson {
  id
}
```

Some information that might be useful to help me help you is:

* What version of `graphql_codegen` are you using?
* Examples of generated code
* Potential build errors.

**Comment by Sander0542** [comment]
Sorry, the schema I proved works. It happens when I am using nested fragments.

```graphql
interface IUser {
    id: ID!
}

type User implements IUser {
    id: ID!
}

type Location {
    id: ID!

    users: [User!]!
}

type Query {
    locations: [Location!]!
}

fragment UserSummary on IUser {
    id
}

fragment LocationWithUsers on Location {
    id
    users {
        ...UserSummary
    }
}

query GetLocations {
    locations {
        ...LocationWithUsers
    }
}
```

**Comment by Sander0542** [comment]
I have a feeling this comment could be the issue https://github.com/zino-hofmann/graphql-flutter/issues/994#issuecomment-1059139588

**Comment by budde377** [comment]
So is this a problem with the data  not being sent to/from your server on runtime, or the built serialisers?

**Comment by Sander0542** [comment]
The query that gets sent to the server doesn't contain the required information like `users.id`

**Comment by budde377** [comment]
This library shouldn’t be manipulating your queries, can you elaborate a
bit on what you mean by

> query that gets sent to the server doesn't contain the required
information

**Comment by Sander0542** [comment]
The query that should get sent to the server is

```graphql
query GetLocations {
    locations {
      __typename
      users {
        __typename
        id
      }
    }
}
```

But the query that is sent is

```graphql
query GetLocations {
    locations {
      __typename
      users {
        __typename
      }
    }
}
```

**Comment by budde377** [comment]
Cheers. The library does no such changes to queries. 

Please make sure you've rebuild your serialisers. If this doesn't work please share the generated file + the original query + an example on how you're calling the query.

**Comment by budde377** [comment]
I'm going to close this issue for now. Let's revisit if you have more information.
