### ISSUE TITLE
How can i change the generation output folder?

### ISSUE THREAD

**Issue by jofgross** [heftapp/graphql_codegen#16]
I would like to customize the output folder for the generated files and could not find a configuration option so far. In my case the destination folder would be /lib/generated/graphql/.
Is there this possibility or a workaround for this?

**Comment by budde377** [comment]
Thanks for reaching out. Right now the generated files are located next to the graphql files, so the only way to achieve this right now is to move the graphql file. 

I'd be open to make this configurable and a PR is appreciated!
