### ISSUE TITLE
Suppor for gql extension files

### ISSUE THREAD

**Issue by tlvenn** [heftapp/graphql_codegen#175]
Hi,

I might have missed the right build.yaml settings but it appears that at the moment it is not possible to name graphql files using the `.gql` extension. I tried playing with `assetsPath` but it did not work.

Am i missing something ?

**Comment by budde377** [comment]
Thanks for reporting @tlvenn, it should now be supported in `0.11.0-beta.7`

**Comment by tlvenn** [comment]
Awesome, thanks !
