### ISSUE TITLE
extraKeywords Option no more works

### ISSUE THREAD

**Issue by Arpit1496** [heftapp/graphql_codegen#181]
After updating the version, the  generated filesdo not append $ in front of keywords.

**Comment by budde377** [comment]
Please provide an example of your configuration and your code.

**Comment by howlingpan** [comment]
Same here, tested with example project, with additional enum QueryMode added to schema.graphql
`type Query {
  fetch_person(id: ID!): Person
}

type Person {
  full_name: String!
  nickname: String
  website: URL
  date_of_birth: ISODateTime
  favorite_parent: Person
  parents: [Person!]
  siblings: [Person!]
  children: [Person!]
  dob: ISODateTime
  events: [ISODateTime]
  events_of_events: [[ISODateTime]]
}

scalar ISODateTime

scalar URL

type Mutation {
  update_person(id: ID!, full_name: String): Person
  update_person_advanced(input: UpdatePersonInput!): Person
}

type Subscription {
  watch_person(id: ID): Person
}

input UpdatePersonInput {
  id: ID!
  full_name: String
  nickname: String
  website: URL
}

enum QueryMode {
  default
  insensitive
}
`

**Comment by budde377** [comment]
Thank you @howlingpan for the reproducible example! It was a huge help in debugging the issue. A fix should be released in `0.11.1`.
