### ISSUE TITLE
Fragment on interface is not working

### ISSUE THREAD

**Issue by radroot1** [heftapp/graphql_codegen#189]
flutter: "3.3.3"
graphql_codegen: 0.11.1
graphql: 5.1.1

schema:
```
interface InterfaceA {
   id: ID!
   name: String!
}

type TypeA implements InterfaceA {
  id: ID!
  name: String!
}

type SomeData {
  data: TypeA!
}
```

query:
```
fragment FragmentA on InterfaceA {
    id
    name
}

query someQuery {
  data {
    ...FragmentA
  }
}
```

Server works just fine - data is there, but its not appearing in QueryResult - not even in .data
When I pull parsedData ->
`type 'Null' is not a subtype of type 'String' in type cast`

In generated code - there is

```
const fragmentDefinitionFragmentA = FragmentDefinitionNode(
  name: NameNode(value: 'FragmentA'),
  typeCondition: TypeConditionNode(
      on: NamedTypeNode(
    name: NameNode(value: 'InterfaceA'),
    isNonNull: false,
  )),
```

if I change `name: NameNode(value: 'InterfaceA'),` `InterfaceA` on  `TypeA` suddenly it's working.

**Comment by g0josh** [comment]
Faced this issue, had to add `__typename` in queries.

**Comment by radroot1** [comment]
Hmm, placed __typename like so 
```
query someQuery {
  data {
    __typename
    ...FragmentA
  }
}
```
it did not worked

**Comment by budde377** [comment]
If the data isn't even present, then it's probably not an issue with the code generator.

**Comment by radroot1** [comment]
Data is present, I see it on http logger.

I solved it just now, it was cache normalization issue. Passed down generted possibleTypesMap and it worked. Didn;t know it was a thing.
Closing the issue

**Comment by ethras** [comment]
> Data is present, I see it on http logger.
> 
> I solved it just now, it was cache normalization issue. Passed down generted possibleTypesMap and it worked. Didn;t know it was a thing. Closing the issue

Seems to be facing the same issue. Can you detail how you solved yours ?
