### ISSUE TITLE
call from json from a object instance

### ISSUE THREAD

**Issue by vincenzopalazzo** [heftapp/graphql_codegen#19]
The actual code generation generates only a factory method to create an object from the JSON.

I would like to ask if adding an object method to fill an instance from a JSON could be cool to have, it should be enabled code like the following one

  ```
Future<T> query<T extends JsonSerializable>({required QueryOptions query}) async {
      var response = await _client.query(query);
      if (response.hasException) {
        throw Exception(response.exception);
      }
      var result = newObject<T>();
      return result.fromJson(response.data!);
  }
```

**Comment by budde377** [comment]
This is actually already the case! Take a look at the generated example here https://github.com/heftapp/graphql_codegen/blob/main/graphql_codegen/example/lib/main.graphql.dart#L145


For the fetch person query

```graphql
query FetchPerson ($id: ID!) {
    fetch_person(id: $id) {
        ...PersonSummary
        parents {
            ...PersonSummary
        }
        children {
            ...PersonSummary
        }
    }
}
```

an extension is created on the GraphQL client

```dart
extension GQLExtensionQueryFetchPerson on graphql.GraphQLClient {
  Future<graphql.QueryResult> queryFetchPerson(
          GQLOptionsQueryFetchPerson options) async =>
      await this.query(options);
  graphql.ObservableQuery watchQueryFetchPerson(
          GQLWatchOptionsQueryFetchPerson options) =>
      this.watchQuery(options);
}
```

this means that you can call the client 

```dart
client.queryFetchPerson(...)
```
which will serialize your response and only accept the right options/variables.

**Comment by budde377** [comment]
It would be nice if we didn't have to call the parsed getter, but that would require changes to the `QueryResult`. I have it on my todo to look into this!

**Comment by vincenzopalazzo** [comment]
>It would be nice if we didn't have to call the parsed getter, but that would require changes to the QueryResult. I have it on my todo to look into this!c

Yes, if you need help on the graphql client-side just ping me, if we can work without a specific implementation of a client for each query, this library enables to autogenerate library like a library to call Github API or other, where the user generates the source code from the query and we use it to call the client.

This means that we can support different version of API

**Comment by budde377** [comment]
@vincenzopalazzo, I've started on a PR here https://github.com/zino-hofmann/graphql-flutter/pull/1013

**Comment by vincenzopalazzo** [comment]
Cool, I will review it as soon as can! thanks

**Comment by budde377** [comment]
Thanks for the review! The `0.6.0-beta.3` version supports the new parsers and you can now parse the data with

```dart
final result = await client.queryYourQuery();
final parsed = result.parsedResult;
```
