### ISSUE TITLE
Get operationName from the query

### ISSUE THREAD

**Issue by g0josh** [heftapp/graphql_codegen#191]
How to get the operationName to pass into the options

get_apples.graphql
```
query GetApples {
  __typename
 id
 name
}

```

later in my code
```
final result = await client.query_Apples(
    Options$Query_Apples(
        operationName: Query_Apples.<...> // I need this to be "GetApples"
        fetchPolicy: ignoreCache
            ? FetchPolicy.networkOnly
            : FetchPolicy.cacheAndNetwork));
```
I am using along with `graphql` client

**Comment by budde377** [comment]
Why do you need this?

**Comment by g0josh** [comment]
I'm an using the operation name to get tokens in the`graphql` client auth link logic. Want a way to get that from the query rather than manually entering a String.

**Comment by budde377** [comment]
You have the document node, so you can extract it from there. There's only going to be a single operation in the document, so this should be easy enough.

**Comment by g0josh** [comment]
Could you provide an example please,  I tried `documentNode.definitions.` but couldn't find anything useful.

**Comment by budde377** [comment]
Something like 

```dart
final name = documentNode.definitions
          .whereType<OperationDefinitionNode>()
          .first
          .name
          .value
```

**Comment by ropez** [comment]
I came here looking for the same.

I wonder, why not have an (optional?) feature that the generated code has a default value for the `operationName`, from the GraphQL document?

**Comment by budde377** [comment]
It has been awhile since I looked at this issue. Do you mind giving an example of your proposed limitation and some context of why you need it?

**Comment by budde377** [comment]
Thanks for the example @ropez  - Try the new option `setOperationName` in version `v1.2.3`

**Comment by ropez** [comment]
Thank you very much for resolving this. We tried it, and it seems to work as expected.

However, we have an issue with using this version, because we have other packages ([hive_generator](https://pub.dev/packages/hive_generator)) that depends on a different version of dart_style.

**Comment by budde377** [comment]
What's the type mismatch?

**Comment by ropez** [comment]
The unmaintained hive/hive_generator packages depend on an older version of dart_style. We managed to resolve it be switching to hive_ce/hive_ce_generator.

Thanks you very much for this 👍
