### ISSUE TITLE
dev dependency missing in readme?

### ISSUE THREAD

**Issue by ChillkroeteTTS** [heftapp/graphql_codegen#194]
Hey all,
I'm new to the dart ecosystem and was trying to get graphql_codegen to run. 
I set up a basic project with a schema.graphql file and a corresponding query (queryX.graphql).

Graphql_codegen was able to generate schema.graphql.dart and queryX.graphql but the latter contained a failing import to queryX.g.graphql. It was a coincidence that I managed to get it running by adding [json-serializable](https://pub.dev/packages/json_serializable) to my pubspec.yaml.

Was my set up wrong or is [json-serializable](https://pub.dev/packages/json_serializable) indeed a dev dependency and it should be added to the readme for newbies like me?

**Comment by budde377** [comment]
Hi, json serializable was removed as a dependency in the latest version. Please check that you're on version 0.11.xx.

**Comment by ChillkroeteTTS** [comment]
that was it - thanks.
