### ISSUE TITLE
Analyzer ^5.0.0

### ISSUE THREAD

**Issue by seanolsen** [heftapp/graphql_codegen#195]
please update analyzer dependency

**Comment by budde377** [comment]
A pr is always highly appreciated

**Comment by seanolsen** [comment]
pls check https://github.com/heftapp/graphql_codegen/pull/196

**Comment by seanolsen** [comment]
Hi,
pls publish new changes to pub.dev

**Comment by budde377** [comment]
I am waiting for an issue to be resolved with pub.dev.
