### ISSUE TITLE
Cast Error

### ISSUE THREAD

**Issue by BaudouinCS** [heftapp/graphql_codegen#198]
Hello,

I've suddenly started getting `_CastError (type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, dynamic>' in type cast)` after coming back to my project after 2 months (and updating everything to the latest).

It's in the generated file `user.graphql.dart`, so I tried a `flutter clean` followed by a `flutter packages pub run build_runner build --delete-conflicting-outputs`, but it hasn't changed anything.

The issue is inside a `fromJson` method:
```dart
...
container: l$container == null
            ? null
            : Query$GatherShares$gatherShares$container.fromJson(
                (l$container as Map<String, dynamic>)),   // the exception raises here
...
```

I've looked up solutions/workarounds a bit, and I found this: https://github.com/google/json_serializable.dart/issues/351#issuecomment-431590383
But that would be useless as this is a generated file.

What do you think about this issue? Let me know if you need more details about it.

Flutter doctor:
```
[√] Flutter (Channel stable, 3.3.7, on Microsoft Windows [version 10.0.19044.2130], locale fr-FR)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.0)
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.71.2)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!
```

**Comment by budde377** [comment]
How are you using the code generator, I.e with witch client?

**Comment by BaudouinCS** [comment]
> How are you using the code generator, I.e with witch client?

I use VS Code.

**Comment by BaudouinCS** [comment]
> Graphql codegen doesn't work by itself. Which graphql client are you using.

https://pub.dev/packages/graphql_flutter

**Comment by budde377** [comment]
Which version of `graphql_flutter` are you using?

**Comment by BaudouinCS** [comment]
^5.0.1

**Comment by mkoehne** [comment]
Any updates on this? 
I have the same error just with Null: 
`type 'Null' is not a subtype of type 'Map<String, dynamic>' in type cast`

graphql_flutter: ^5.1.1-beta.3

**Comment by budde377** [comment]
> ^5.0.1
> 
> 

Try and update your client

**Comment by budde377** [comment]
> Any updates on this? 
> 
> I have the same error just with Null: 
> 
> `type 'Null' is not a subtype of type 'Map<String, dynamic>' in type cast`
> 
> 
> 
> graphql_flutter: ^5.1.1-beta.3

This is not the same error. Null is not a subtype of map, so something in the expected data is wrong. Please create a new issue with your queries.
