### ISSUE TITLE
Naming Separator do not change the Options and variables when generate

### ISSUE THREAD

**Issue by Kiruel** [heftapp/graphql_codegen#199]
Using naming separator:
`namingSeparator: '___'`

Should have:
`graphQLClient.query___GetUser(Options___Query___GetUser(variables: Variables___Query___GetUser ...`

But got:
`graphQLClient.query___GetUser(Options$Query___GetUser(variables: Variables$Query___GetUser ...`

Not sure if it's bug of not.

**Comment by addhayam** [comment]
I got the same problem.
