### ISSUE TITLE
query on graphql client return an incomplete value

### ISSUE THREAD

**Issue by vincenzopalazzo** [heftapp/graphql_codegen#20]
I really sorry if I'm writing another issue here, I'm testing some of my ideas and I'm using this library to generate the graphql query compatible with graphql client.

However, I'm not able to run a complex issue in the Github API, in particular, I'm running the following [query](https://github.com/vincenzopalazzo/octokit.dart/blob/main/test/queries/github.commits.graphql) but I got some null errors during the iteration over the response object.

These are two tests that make the same jobs, but only one works, more on the stack trace [here](https://github.com/vincenzopalazzo/octokit.dart/runs/4875908269?check_suite_focus=true#step:5:18)

```
    test('run a query', () async {
      var rawClient = await makeRawClient(token: token!);
      var query = QueryOptions(document: gql(commitQuery), variables: {
        "owner": "vincenzopalazzo",
        "repo": "octokit.dart",
      });
      var response = await rawClient.query(query);
      var edges = response.data!["repository"]!["refs"]!["edges"]!;
      expect(edges.length, 1);
      edges.forEach((element) {
        expect(element["node"], isNotNull);
      });
    });

    test('run a query and decode the result in a Object', () async {
      var response = await client!.query(
          query: GQLOptionsQueryLastCommits(
              variables: VariablesQueryLastCommits(
                  owner: "vincenzopalazzo", repo: "octokit.dart")));
      var query = QueryLastCommits.fromJson(response);
      expect(query.repository!.refs!.edges!.length, 1);
      query.repository!.refs!.edges!.forEach((element) {
        expect(element!.node, isNotNull);
      });
    });
```

In this case, the following test assert fails

```
query.repository!.refs!.edges!.forEach((element) {
        expect(element!.node, isNotNull);
      });
```

**Comment by budde377** [comment]
I haven't looked too much into it yet, but because you have these fragment spreads, try and add the `addTypename` option in your build config:

```
targets:
  $default:
    builders:
      graphql_codegen:
        options:
          addTypename: true
          clients:
            - graphql

```

**Comment by vincenzopalazzo** [comment]
I will try it later today, thanks

**Comment by vincenzopalazzo** [comment]
It just works, can you explain what is happening with this `addTypename`?

**Comment by budde377** [comment]
Yes, so because you're using fragments which are conditional on the type of the object it spreads, we need to provide a typename to let it know where to store the data. If it does not have this it'll assume that the fragment spread doesn't match the type and as such not store the data making it null. 

The addTypename setting will add the __typename field selection to every object, giving the cache the best conditions to resolve this (together with possibleTypes).

I am considering making this enabled by default.

**Comment by vincenzopalazzo** [comment]
Cool thanks

>I am considering making this enabled by default.

Cool be a good things to hide from the user view point IMO
