### ISSUE TITLE
Query variables can't be null

### ISSUE THREAD

**Issue by BaudouinCS** [heftapp/graphql_codegen#200]
Hello,

Sometimes variables _need_ to be null, but this package actually generates code that won't let you have this case.
Here is some generated code where the problem comes from:
```
factory Variables$Query$GatherAssets({String? scope, String? scopeId}) =>
      Variables$Query$GatherAssets._({
        if (scope != null) r'scope': scope,
        if (scopeId != null) r'scopeId': scopeId,
      });
```
We need to get rid of these `if (scope != null)` and `if (scopeId != null)` if we want our variables to be sent as a true null value.

**Comment by BaudouinCS** [comment]
Omitted this in my reading, issue solved: https://github.com/heftapp/graphql_codegen/tree/main/packages/graphql_codegen#null-and-input-serializers

**Comment by LiamKarlMitchell** [comment]
It still kind of seems like a bug, if the type is nullable then it should not do the check?
```
if (something != null)
```
