### ISSUE TITLE
Empty schema.graphql.dart is getting generated.

### ISSUE THREAD

**Issue by FirdousNath** [heftapp/graphql_codegen#201]
I am using latest version. Below is my schema.graphql file

[schema.txt](https://github.com/heftapp/graphql_codegen/files/9962585/schema.txt)

**Comment by budde377** [comment]
Please make sure you have the right file extensions and file locations. See the readme for more information

**Comment by FirdousNath** [comment]
I am using schema.graphql file only located inside lib/grapghql folder. since GitHub wasn't allowing me to attach .graphql file I uploaded txt

**Comment by budde377** [comment]
Are you able to create a small repo with a reproducible example?
