### ISSUE TITLE
Can you provide remote schema support?

### ISSUE THREAD

**Issue by Zane0816** [heftapp/graphql_codegen#202]
Suppose I want to use a remote schema like the [GitHub Public schema](https://docs.github.com/public/schema.docs.graphql).
I need to redownload every time when it changes.
So can you provide a configuration that can automatically generate the schema for me every time I build.
Or some websites do not provide the schema download address, but provide the ability to query the schema
use `query IntrospectionQuery` 
It would be extremely convenient to have these

**Comment by budde377** [comment]
There are many projects allowing you to fetch graphql schemas through introspection, e.g., https://github.com/prisma-labs/get-graphql-schema.

**Comment by Zane0816** [comment]
I don't think it's a good idea.
To use these I have to have the node.js runtime and also write a pre-execute script

**Comment by budde377** [comment]
Okay. The point is that this shouldn't be in this tool.

**Comment by mwahlhuetter** [comment]
If anyone stumbles upon this:
The easiest solution, if you are using Android Studio, would be to install the GraphQL plugin and configure it to save the remote schema in a local file.
See [https://github.com/JetBrains/js-graphql-intellij-plugin#local-introspection-schemas](https://github.com/JetBrains/js-graphql-intellij-plugin#local-introspection-schemas)
