### ISSUE TITLE
code generation is taking more than 30 mins

### ISSUE THREAD

**Issue by krishnatejakanchi** [heftapp/graphql_codegen#204]
My company is using hasura graphql as backend. To generate models from schema, I am using graphql_codegen package. My schema has 99577 lines of code. I am keeping seperate .graphql file for every page, which will contain mutations, queries & subscriptions for that page. It is taking 25-30 mins for me to run build_runner build. It is reaching to 50 mins, if i run the build command after flutter clean. Is it happening to any of you too ? Can you share how much time it is taking for you ?

https://pasteboard.co/pEPkUZrzjqNK.png

Note:
- Mine is m2 pro 8gb variant
- I am using `flutter pub run build_runner watch --delete-conflicting-outputs` command.

**Comment by KlausJokisuo** [comment]
@krishnatejakanchi Have you tried optimizing the build_runner using build.yaml?

**Comment by krishnatejakanchi** [comment]
@KlausJokisuo Yes, I tried, but still same time. Actually our project got more big since i created this issue and it's taking 1 hour now.

Let me know whatever it is needed to understand this issue, I will provide.

This is making my company to consider shifting away from Flutter.

**Comment by KlausJokisuo** [comment]
@krishnatejakanchi Can you show us the build.yaml file? Also, so you use other code generators?

**Comment by krishnatejakanchi** [comment]
@KlausJokisuo 

`targets:
  $default:
    builders:
      graphql_codegen:
        generate_for:
          - lib/**.graphql
        options:
          namingSeparator: "_"
          addTypenameExcludedPaths:
            - subscription
          scalars:
            DateTime:
              type: DateTime
            date:
              type: DateTime
            uuid:
              type: String
            timestamptz:
              type: String
            timetz:
              type: String
            _text:
              type: StringArray
              fromJsonFunctionName: stringArrayFromJson
              toJsonFunctionName: stringArrayToJson
              import: package:user/graphql/scalars/scalar.dart
            _int4:
              type: IntArray
              fromJsonFunctionName: intArrayFromJson
              toJsonFunctionName: intArrayToJson
              import: package:user/graphql/scalars/scalar.dart
          clients:
            - graphql
            - graphql_flutter

      freezed:
        generate_for:
          - lib/**.state.dart
          - lib/**.params.dart

      hive_generator:
        generate_for:
          - lib/db/db.dart

      slang_build_runner:
        generate_for:
          - lib/i18n/strings.i18n.json

      json_serializable:
        generate_for:
          - lib/**.state.dart
          - lib/db/db.dart
          - lib/**.params.dart
        options:
          include_if_null: false
`

**Comment by KlausJokisuo** [comment]
@krishnatejakanchi Can you try running the runner with --verbose flag?

This way we could check what is the actual package which is consuming this much time.

**Comment by budde377** [comment]
If there's any way you can share your schema and operations with me, e.g. in a private repo, then I will be more than happy investigating this.

**Comment by krishnatejakanchi** [comment]
https://github.com/krishnatejakanchi/graphql-codegen-project-review/invitations

I uploaded the schema and all the operations we are using in this repo. Please let me know if any further info is required.

**Comment by danw8989** [comment]
I am having the same problem, taking to long
my build.yaml
`
targets:
  $default:
    builders:
      graphql_codegen:
        options:
          outputDirectory: ./
          assetsPath: lib/core/graphql/**.graphql
          scopes: 
            - lib/core/graphql/main_schema/**.graphql
            - lib/core/graphql/data_schema/**.graphql
          namingSeparator: ""
          includeIfNullOnInput: false
          addTypenameExcludedPaths: [subscription]
          extraKeywords: 
            - String
          clients:
            - graphql
            - graphql_flutter
          scalars:
            timestamptz:
              type: DateTime
              fromJsonFunctionName: fromGraphQLTimestamptzToDartDateTime
              toJsonFunctionName: fromDartDateTimeToGraphQLTimestamptz
              import: package:production_management/core/graphql/scalars/coercers.dart
            date:
              type: DateTime
              fromJsonFunctionName: fromGraphQLDateToDartDateTime
              toJsonFunctionName: fromDartDateTimeToGraphQLDate
              import: package:production_management/core/graphql/scalars/coercers.dart
            time:
              type: DateTime
              fromJsonFunctionName: fromGraphQLTimeToDartDateTime
              toJsonFunctionName: fromDartDateTimeToGraphQLTime
              import: package:production_management/core/graphql/scalars/coercers.dart
            smallint:
              type: int
            interval:
              type: Duration
              fromJsonFunctionName: fromGraphQLIntervalToDartDuration
              toJsonFunctionName: fromDartDurationToGraphQLInterval
              import: package:production_management/core/graphql/scalars/coercers.dart
            uuid:
              type: String
            json:
              type: Map<String,dynamic>
            numeric:
              type: Decimal
              fromJsonFunctionName: fromGraphQLNumericToDartDecimal
              toJsonFunctionName: fromDartDecimalToGraphQLNumeric
              import: package:production_management/core/graphql/scalars/coercers.dart 
            jsonb:
              type: Map<String,dynamic>
            bytea:
              type: int
            bigint:
              type: int
            citext:
              type: String
            float8:
              type: double
`

**Comment by budde377** [comment]
I've released a fix that should significantly improve performance. The most time-intensive step is now parsing the GraphQL files. Please try it out in the pre-release.

**Comment by danw8989** [comment]
Wow, that's great news, hope it helps.

**Comment by krishna-pietech** [comment]
It feels so good to see this


```[INFO] 4m 22s elapsed, 1738/1749 actions completed.
[INFO] Running build completed, took 4m 23s

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 341ms

[INFO] Succeeded after 4m 23s with 441 outputs (2038 actions)
```

when it used to be 

```
[INFO] 1h 7m elapsed, 406/413 actions completed.
[WARNING] No actions completed for 2m 6s, waiting on:
  - graphql_codegen on lib/pages/onboarding/pincode_collect/pincode_collect.graphql
  - graphql_codegen on lib/pages/onboarding/forgot_pincode/forgot_pincode.graphql
  - graphql_codegen on lib/pages/onboarding/otp_verification/otp_verification.graphql
  - graphql_codegen on lib/pages/onboarding/email_verification/email_verification.graphql
  - graphql_codegen on lib/pages/onboarding/avatar_picker/avatar_picker.graphql
  .. and 2 more
```

Thanks @budde377

**Comment by budde377** [comment]
@krishna-pietech, I am very happy that this worked for you! I've just had another go at optimizing GraphQL parsing which should further improve the run-time. This is released as 0.12.0-beta.12.

**Comment by krishnatejakanchi** [comment]
Now build_runner is taking 1 more minute less with this new version. Thanks again @budde377 .

**Comment by danw8989** [comment]
Yeah, it is like 10 times faster for me, thanks a lot. Just a remainder that performance is not that important until it is. 😄 
And you say you optimized it even further, dang @budde377 you on a roll 🥳

**Comment by shivanipietech** [comment]
It feels so good to see the execution in 4 mins only.. You save our more than 1 hour. Thanks @budde377
