### ISSUE TITLE
graphql_flutter Options method is not generated?

### ISSUE THREAD

**Issue by LiamKarlMitchell** [heftapp/graphql_codegen#205]
In the generated files it gives me a bunch of errors that the Options Query method is not found.
Am I doing something wrong?

Error: Method not found: 'Options$Query$GetMe()

schema.graphql
```graphql
schema {
  query: Query
}

type Query {
  me: User
}

type User {
  id: ID!
  firstName: String
  lastName: String
  city: String
  email: String!
  avatar: String
}
```

getMeQuery.gql
```graphql
query GetMe {
    me {
        id
        firstName
        lastName
        email
        avatar
    }
}
```

![image](https://user-images.githubusercontent.com/1968109/201385969-f1d72a4b-f1e0-4f36-82ef-daba34c248d8.png)

**Comment by LiamKarlMitchell** [comment]
Ah! I had to use the graphql client as well. I thought they were separate packages/clients.
But they seem to be complementary one just being a wrapper for flutter and one for dart in general doh!.
Was confused as I saw the optional in the documentation and only remembered adding the graphql_flutter package my bad I guess.

**Comment by agrosner** [comment]
seems like a silly footgun. Shouldnt the library throw an error in this situation? or at least WARN

**Comment by LiamKarlMitchell** [comment]
I suppose that would be a nice to have :)

**Comment by budde377** [comment]
PRs are always appreciated

**Comment by LiamKarlMitchell** [comment]
Ok sure good reasoning, I'll reopen this and have a thought sometime although I'm new to flutter/dart hah.

I can think of three solutions maybe?
A) If graphql_flutter client is present, also confirm graphql client is present (or maybe it can be auto added somehow hmm).
B) If graphql_flutter client is present, and graphql client is not present error/warn with an informative message.
C) Do nothing, or perhaps improve readme to indicate that if using flutter need other one as it was the optional part that caused me some confusion here.

**Comment by budde377** [comment]
I think (A) sounds like a reasonable approach! Maybe take a look at where the config is being used, then you can implement some magic logic here.

**Comment by LiamKarlMitchell** [comment]
Ok figured it out.
