### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by tjarvstrand** [heftapp/graphql_codegen#206]
The following definitions causes `graphql_codegen` to emit `Null check operator used on a null value` during code generation:
```
schema {
  mutation: Mutations
}

type Mutations {
  bla: EventPublic
}

interface Event {
  subscription: EventSubscription
}

type EventPublic implements Event {
  owner: UserPublic!
  subscription: EventSubscription
}

type EventSubscription {
  notifyFor: String!
}

type UserPublic {
  username: String!
}

fragment EventFragment on Event {
  ...on EventPublic {
    owner { ...UserPublicFragment }
  }
  subscription {
    notifyFor
  }
}

fragment UserPublicFragment on UserPublic {
  username
}

mutation Bla {
  bla { ...EventFragment }
}
```

The error seems to be caused by the nested `notifyFor`-key in `EventFragment.subscription`, removing that or breaking it out to its own fragment (eg. `subscription { ...SubscriptionFragment }`) causes the error to go away.

**Comment by budde377** [comment]
Thank you for reporting this. I've identified the underlying issue and will work on a fix.
