### ISSUE TITLE
Unable to get fields from fragment's parent class 

### ISSUE THREAD

**Issue by sugam-singh** [heftapp/graphql_codegen#209]
Unable to get fields from the fragment's parent class when the fields are different.

```graphql
# schema.graphql

type HostAccount implements UserV2 {
  hasShop: Boolean!
}

interface UserV2 {
  name: String
}
```

```graphql
# user_query.graphql

query userV2 {
    userV2 {
        name
        ... on HostAccount {
            hasShop
        }
    }
}
```
After running the build_runner, I tried using the generated model.

```dart
// fetch_user.dart

void fetchUser() {
  Map<String, dynamic> responseFromApi = fetchUserV2FromApi();
  Query$userV2$userV2 user = Query$userV2$userV2.fromJson(responseFromApi);
  print(user.name);
  print(responseFromApi['hasShop']);
  if (user is Query$userV2$userV2$$HostAccount) print(user.hasShop);    
        // Error: The getter 'hasShop' isn't defined for the type 'Query$userV2$userV2'
}
```
What's the correct way to get the `hasShop` from the `user`?

Also, the `fromJson` factory method of `Query$userV2$userV2$$HostAccount` has no usage in the generated `user_query.graphql.dart` file.

**Comment by budde377** [comment]
This is invalid GraphQL

```graphql
type HostAccount implements UserV2 {
  hasShop: Boolean!
}

interface UserV2 {
  name: String
}
```

You need to explicitly implement all fields from the interface: [spec](https://spec.graphql.org/October2021/#IsValidImplementation())


so your implementation becomes


```graphql
type HostAccount implements UserV2 {
  hasShop: Boolean!
  name: String
}

interface UserV2 {
  name: String
}
```

**Comment by rohanjsh** [comment]
Hey @budde377, thanks for this amazing library!!, appreciate your efforts!. 

I am a team mate of @sugam-singh, following up on the thread.
We are facing some issue for generating code for interfaces, it'll be of great help if you can suggest.

We have now validated our graphql schema:
```graphql
#schema.graphql
type HostAccount implements UserAccount {
  hasShop: Boolean!
  name: String
}

interface UserAccount {
  name: String
}


#query
type Query {
   myAccount: UserAccount!
}
```

Client side Query:
```graphql
query myAccount {
    myAccount {
        name
        ... on HostAccount {
            hasShop
        }
    }
}
```

If I want to access hasShop from the above query, what is the way to do that?
Ideally:
```dart
Query$myAccount model = Query$myAccount.fromJson(
          _response.data,
        );
var val = model.myAccount.hasShop; //this should get me the value, but this cannot be done, how should I access this?
```

Let me know, thank you!
