### ISSUE TITLE
Null error in query with fragment

### ISSUE THREAD

**Issue by mkoehne** [heftapp/graphql_codegen#213]
I get this error on the first call to the backend: 
`type 'Null' is not a subtype of type 'Map<String, dynamic>' in type cast`
The second time it gets called it works because the json result has a vaule inside.

I use these versions: 
graphql: ^5.1.1
graphql_codegen: ^0.11.2
graphql_flutter: ^5.1.1-beta.5

The query looks like this:
`query GetEvents {
    events {
        ...Event
    }
}`

The generated code for the query looks like this:
`factory Query$GetEvents.fromJson(Map<String, dynamic> json) {
    final l$events = json['events'];
    return Query$GetEvents(
        events: (l$events as List<dynamic>).map((e) => Fragment$Event.fromJson((e as Map<String, dynamic>))).toList());
  }`

e is null and Fragment$Event can not read null.
<img width="908" alt="null_error" src="https://user-images.githubusercontent.com/15260431/206144324-30b7d765-2bae-4fdf-a127-48e030a7fa4d.png">

My quick fix was to just check if the json or e is null and then return an empty list.

`factory Query$GetEvents.fromJson(Map<String, dynamic> json) {
    final l$events = json['events'];
    if (l$events == null || (l$events as List<dynamic>).where((element) => element == null).isNotEmpty) {
      return Query$GetEvents(
        events: <Fragment$Event>[],
      );
    }
    return Query$GetEvents(
        events: (l$events as List<dynamic>).map((e) => Fragment$Event.fromJson((e as Map<String, dynamic>))).toList());
  }`

Would it be possible to have such a null check be generated automatically?

Thank you.

**Comment by budde377** [comment]
What does your schema look like?

**Comment by budde377** [comment]
So the schema defines that the array can’t be null and can’t contain null,
so this is why the codegen will expect a map.

I don’t know why your array contains null. Is it from the server?

**Comment by mkoehne** [comment]
Yes is looks like a server problem.
I changed the Event object on the server to be nullable and I don´t get the error anymore.
I still don´t know why the server sends null for something that should never be null.

Thank you very much.

**Comment by radicand** [comment]
Is there a recommended way to work around this? I am running into the same issue using Hasura, fields can return null due to field-level permissions checks disallowing access. Schema reports non-nullable, but response may be null if there is such a permission check present and it fails access. There's an [open issue on the Hasura side](https://github.com/hasura/graphql-engine/issues/9355) but it would be helpful to know how to sidestep this issue in the interim as it is blocking our development efforts.

**Comment by budde377** [comment]
Can you mark the field as nullable on your server?

**Comment by radicand** [comment]
@budde377 thanks, I gave this a go and it worked as intended - marking the id reference as nullable did translate to the relation being nullable. This may be the way to go until Hasura comes up with a better solution. I appreciate the nudge.
