### ISSUE TITLE
DateTime should be converted to UTC before calling toIso8601String

### ISSUE THREAD

**Issue by sperochon** [heftapp/graphql_codegen#218]
Hello,

Thanks for your lib.

Generated code for date time in toJson is :
`result$data['startDate'] = l$startDate?.toIso8601String();`

I think it should be:
`result$data['startDate'] = l$startDate?.toUtc().toIso8601String();`

Because in Dart, there is "No TimeZone information in toIso8601String of DateTime" (see https://github.com/dart-lang/sdk/issues/43391)

So, `l$startDate?.toIso8601String();` gives a LOCAL String datetime value without TZ offset as in this example: "2020-09-10T09:03:00.000"

The graphQL server can't know what time is it (and by default import it as a UTC datetime which is wrong here!)

I could add `.toUtc()` to the dates in my code but I think it is a mistake to not do it in the generated code. Please correct me if I'm wrong.

Thanks!

**Comment by budde377** [comment]
Interesting issue! The current implementation follows the implementation from json serialisable. I would be curious to learn why they didn't convert to utc.

As a quick fix, you can provide custom serialisers for the scalar.

**Comment by sperochon** [comment]
Interesting, as you said! ;-)
I also use directly json_serializable but I use my own custom converter for Datetime and so didn't see the problem.

My 2 cts:

Maybe they do not enforce UTC conversion in json_serializable because there is no major standard use case that need it. Some dev can only want to do thing like this :
`anotherJohn = Person.fromJson(john.toJson())`

In graphql_codegen, the standard use case (99% of time) will be to communicate between 2 different devices (unknown timezones). So the need to enforce the conversion to UTC.

I'll take a look at making custom serialisers, thanks!

**Comment by budde377** [comment]
We should follow the `json_serializable` implementation here and instead encourage people to supply their own serialization strategies.
