### ISSUE TITLE
Code generation is broken on Flutter 2.10 starting from 0.11.1

### ISSUE THREAD

**Issue by sperochon** [heftapp/graphql_codegen#219]
Hi again ;-)

I'm using Flutter 2.10 (dart 2.16)
Code generation is broken when upgrading from 0.11.0 to 0.11.1 
```
[WARNING] ../../../../sdk/flutter/.pub-cache/hosted/pub.dartlang.org/graphql_codegen-0.11.1/lib/src/printer/base/input.dart:184:5: Error: Method not found: 'declareFinal'.
    declareFinal(resultDataVariableName)
    ^^^^^^^^^^^^
```

Thanks!

**Comment by budde377** [comment]
Make sure you update dependencies of codegen, namely the code builder. If you delete your package lock file and install again it should work

**Comment by sperochon** [comment]
Thanks, but I already use the last compatible version of code_builder for Flutter 2.10 (dart 2.16) which is 4.1.0 (dart 2.12).
The others required dart 2.17 (Flutter 3)
https://pub.dev/packages/code_builder/versions

Maybe you should update your pubspec.yaml to :
```
environment:
  sdk: '>=2.17.0 <3.0.0'
```

"flutter pub get" would then failed

**Comment by budde377** [comment]
Fair!
