### ISSUE TITLE
build option to not add __typename to top-level selection set for subscriptions

### ISSUE THREAD

**Issue by klondikedragon** [heftapp/graphql_codegen#22]
First, I'm impressed and excited by this package! This is the only dart package I've come across that can actually successfully generate code from a GraphQL schema generated by [Hasura](https://hasura.io/) -- these schemas are a bit more complex (supporting lots of operators, search conditions, methods for paging, etc) and it tripped up other dart gql code generators I've tried. Nicely done!

Also, even though it's not documented to work, it looks like it will actually parse and generate code for subscriptions! (not the client part yet, but that's OK). That was another happy surprise!

Hasura only supports one top-level field for subscriptions (for queries/mutations multiple top-level fields are fully supported without issue). In the Hasura schema, this top-level field would correspond to a table or view in the source database.

If you had some GraphQL like:
```graphql
fragment Friend on ...

subscription ListenToFriends($user_id: String!) {
  user_friends(where: {user_id: {_eq: $user_id}}) {
    ...Friend
  }
}
```

Then with `addTypename: true` in build.yaml this will result in generated code with a `SelectionSetNode` that contains two `FieldNode`s -- one for `user_friends` and then another for `__typename`:

```dart
FieldNode(
            name: NameNode(value: '__typename'),
            alias: null,
            arguments: [],
            directives: [],
            selectionSet: null)
```

The other __typename fields that are automatically added are perfectly OK, if I manually remove this top-level __typename filed node from the generated `DocumentNode`, then the subscription is able to execute successfully. If the generated code is unmodified, then when the subscription is run, Hasura responds with this error message instead:

```
[{extensions: {path: $, code: validation-failed}, message: subscriptions must select one top level field}]
```

I don't know if this may be a problem common to other GraphQL server/subscription implementations. Arguably Hasura should recognize that __typename is not really trying to subscribe to a second field set, and I'll raise the issue there for consideration there.

I wanted to see if it made sense here to add another build.yaml option, something like `omitTopLevelSubscriptionTypename: true` (off by default?), that would tell the code generator to not add __typename just on the top-level of a subscription, so that the auto-generated code out of the box would work with Hasura subscriptions. Or perhaps this field might never be needed at the top-level for a subscription and could always be omitted potentially? What do you think?

**Comment by budde377** [comment]
@klondikedragon, interesting use-case! Do you think it would make sense to create a general option like

```
addTypenameExcludedTypes: ["Subscription"]
```

for a more general case? I imagine other servers might treat e.g. `Query` or `Mutation` similarly.

**Comment by budde377** [comment]
Actually, excluding types will not be feasible. Here's what I'm working on

```
addTypenameExcludedPaths: ["subscription", "subscription.foobar"]
```

The first will exclude adding typenames to subscriptions, the next to the `foobar` field selection under the `subscription`.

**Comment by orestesgaolin** [comment]
Just wanted to add comment for anyone looking by the exact exception message. This resolves:

```
subscriptions must select one top level field
```

**Comment by poka-IT** [comment]
> ```
> addTypenameExcludedPaths: ["subscription", "subscription.foobar"]
> ```

Bro, thank you so much, I spent hours on this ...
This simple line fixed it.
Hasura...
