### ISSUE TITLE
Graph QL identifier with same name as a type produced invalid dart code

### ISSUE THREAD

**Issue by ju851zel** [heftapp/graphql_codegen#222]
When generating a gql schema where an identifier is names like a dart type (e.g. String) the produced dart will be invalid.

I notice this when working with hasura. There also exists an [issue](https://github.com/hasura/graphql-engine/issues/8617).

A schema like that:
```graphql
input jsonb_cast_exp {
  String: String_comparison_exp
}
```

Produces invalid dart code because the a generated getter will have the name `String` and therefore is not valid.
Because it is valid in graphql to name your identifier `String` this should be fixed in the code generator.

Proposal:
Check when a graphql identifier is the same as a known type of the core library and if so rename it to `_{Name}`. E.g. `String`-> `_String`. Also log the renaming for the user as a warning.

**Comment by budde377** [comment]
Check the `extraKeywords` option in the readme, it is created exactly for this purpose.
