### ISSUE TITLE
Deeply nested fragments not working

### ISSUE THREAD

**Issue by KlausJokisuo** [heftapp/graphql_codegen#231]
For some reason If I have deeply nested Fragments. Like 3 levels, the fragments are not sent in the query.
I'm using the fragments to get more meaningful type names.

Any idea what might be the reason?

**Comment by KlausJokisuo** [comment]
I'll try as soon as possible to get you one.

What is the correct naming for fragments?

For example if I have a type Team, can I use 

```
fragment Team on Team {
  id
  name
  teamMembers {
    user {
      ...TeamMember
    }
  }
}
```

Also can I use the same fragment name in multiple files without them conflicting?

**Comment by budde377** [comment]
You can use the same name as types, but stuff will get wired if you make
cyclic fragments or have two fragments with the same name.

**Comment by KlausJokisuo** [comment]
Solved the issue, the problem was that I was using the same naming for fragments in multiple files.
Do you know any workaround for this one?

The main concern for me is the type names, they are huuuuge without fragments. 🤔

**Comment by budde377** [comment]
Usually I try and come up with some naming scheme. Like the name of the widget using it prefixed with the type. This scales quite well.
