### ISSUE TITLE
Should mutation constructors require a $__typename parameter to be provided manually?

### ISSUE THREAD

**Issue by jeroldalbertson-wf** [heftapp/graphql_codegen#235]
I didn't know if this was intended, but generated Mutation operation classes require a $__typename parameter to be provided in their constructors. Is it normal for consumers to deviate from the type name declared in the source schema? How feasible would it be for $__typename to be removed from the constructor, or made optional with a reasonable default value?

```graphql
mutation Update($id: ID!) {
    update(id: $id) {
        id
    }
}
```
generates the following dart code
```dart
class Mutation$Update {
  Mutation$Update({
    required this.update,
    required this.$__typename,
  });

  final Mutation$Update$update update;

  final String $__typename;
  // ...
}

// consumer writes:

final mutation = Mutation$Update(
    update: Mutation$Update$update(
      id: myId,
      $__typename: 'update',
    ),
    $__typename: 'Update',
  );
```

while the following would be more convenient
```dart
class Mutation$Update {
  Mutation$Update({
    required this.update,
  });

  final Mutation$Update$update update;

  const String $__typename = 'Update';
  // ...
}

// consumer writes:

final mutation = Mutation$Update(
    update: Mutation$Update$update(
      id: myId,
    ),
  );
```

Thanks again for all your work on this library. It's been a pleasure to work with. :)

**Comment by budde377** [comment]
Maybe we can, but I would be interested in learning how you are using the framework and when this is a problem. The serializers are rarely initiated manually, which is why not having default values has not been a problem so far. Why do you need to initiate the serializers manually?

**Comment by jeroldalbertson-wf** [comment]
@budde377 Thanks for the replies. This mainly comes up for my team while building expected values for test. As well as when providing optimistic values.

**Comment by budde377** [comment]
Thanks, I'm certain we can accommodate this. Let me have a go at it.

**Comment by budde377** [comment]
Released in latest pre-release.
