### ISSUE TITLE
Bug: wrong document generated for nested fragments & unions

### ISSUE THREAD

**Issue by bogdibota** [heftapp/graphql_codegen#237]
There seems to be a problem when you generate a query document that uses nested fragments and unions. 
```
query GetFullProfile($getId: ID!) {
  profile {
    get(id: $getId) {
      ...FullProfile
    }
  }
}

fragment FullProfile on Profile {
  id

  featuredMedia {
    ...Media
  }
}
fragment Media on Media {
  ... on Image {
    id
    src
    thumbnailSrc
  }
  ... on Video {
    id
    src
  }
}
```

The above **query works just fine** in Apollo Studio Sandbox.

With `graphql_codegen`:
 - ✔️ code generation is successful
 - ✔️ query is successful
 - ✔️ fragment classes and `fromJson` methods are correct
 - ❌ document object seems to be broken. Looks like the response only includes `__typename` on `featuredMedia`, and not `id, src, ...`. The query executes just fine, but `Fragment$...$$Image.fromJson()` throws `<type 'Null' is not a subtype of type 'String' in type cast`

However, removing the `Media` fragment and inlining the query works just fine:
```
query GetFullProfile($getId: ID!) {
  profile {
    get(id: $getId) {
      ...FullProfile
    }
  }
}

fragment FullProfile on Profile {
  id

  featuredMedia {
    ...on Video {
      id
      src
    }
    ...on Image {
      id
      src
      thumbnailSrc
    }
  }
}
```

If it helps, the relevant schema looks like this:
```
type Image {
    id: ID!    
    src: String!
    thumbnailSrc: String!
}

type Video {
    id: ID!
    src: String!
}

union Media = Image | Video

type Profile {
  id: ID!
  featuredMedia: [Media!]!
}
```

**Comment by budde377** [comment]
> ❌ document object seems to be broken. Looks like the response only includes __typename on featuredMedia, and not id, src, .... The query executes just fine, but Fragment$...$$Image.fromJson() throws <type 'Null' is not a subtype of type 'String' in type cast

I've tried to re-produce your issue in #238 and it seems right to me. Check that you are on the latest (beta) version or provide a reproducible example.

**Comment by bogdibota** [comment]
You are right. Everything seems to be fine there.

I created a debug link for the `GraphQLClient` and the document and raw response seem correct.

Maybe this is a caching issue? Either way, codegen looks perfectly fine.

Thanks for your help!

**Comment by bogdibota** [comment]
finally got around to solving this. apparently, it's related to the `normalize` package needing the `possibleTypesMap` to correctly update the cache for fragments on union types.

see https://stackoverflow.com/a/70977414 for an explanation

```dart
import 'package:[...]/__schema.graphql.dart'; // generated via graphql_codegen

// ...

  final graphQLClient = GraphQLClient(
    link: link,
    cache: GraphQLCache(
      possibleTypes: possibleTypesMap, // <-- added this line
    ),
  );
```
