### ISSUE TITLE
Add onCompleted and onError callback options to Query

### ISSUE THREAD

**Issue by sandrocsimas** [heftapp/graphql_codegen#242]
Hey, thanks for this awesome library.
Is there a way for you to add those two recent callbacks to the query options?
I can also try to create a PR if you show me which files I need to change.

**Comment by budde377** [comment]
[Here](https://github.com/heftapp/graphql_codegen/blob/0fd92bfdd2a130951a9330433101d0f7f078279c/packages/graphql_codegen/lib/src/printer/clients/graphql.dart#L286) is how the mutation options are generated. We will need to do something similar to the query options.
