### ISSUE TITLE
Make optional optimisticResponse parameter typed

### ISSUE THREAD

**Issue by KlausJokisuo** [heftapp/graphql_codegen#243]
Would it be possible to make optimisticResponse parameter typed?

It would make it a bit easier to create optimisticResponses.

Keep up the good work :)

**Comment by KlausJokisuo** [comment]
This is a bit related to this https://github.com/heftapp/graphql_codegen/issues/235

**Comment by budde377** [comment]
Everything is possible!

**Comment by KlausJokisuo** [comment]
> Everything is possible!

Awesome! Let me know If you need use cases or examples 👍
