### ISSUE TITLE
Codegen breaks when using extend keyword in schema

### ISSUE THREAD

**Issue by kvinsu** [heftapp/graphql_codegen#244]
Hey there, I have a question regarding the option to extend a graphql type from another `.graphql`-file via `extend`: 
Does the library `codegen_graphql` support that or did I oversee a mistake in the configuration or something like that?

A simple reproducible example would be the following (copied from the issue https://github.com/heftapp/graphql_codegen/issues/120, where it was mentioned but never tested):

```graphql
# user.graphql
type User {
  id: ID!
  name: String!
}

type Query {
  user(id: ID!): User
}
```

```graphql
# user.graphql
type User {
  id: ID!
  name: String!
}

extend type Query {
  user(id: ID!): User
}
```

```graphql
# query.graphql
query User($userId: ID!) {
  user(id: $userId) {
    id
    name
  }
}
```

When running the standard command ```flutter clean && flutter pub get && dart run build_runner build --delete-conflicting-outputs```, the following error for all `.graphql`-files (3x in this case) will be thrown:
```
[SEVERE] graphql_codegen on graphql/queries/query.graphql:

Invalid GraphQL: Failed to find type for field user on Query
```

My suspicion is that the library `graphql_codegen` does not support the `extend` graphql function yet, however, noone created an issue regarding this problem yet, so I was a bit sussy whether it was me who made a mistake.

Any help is very appreciated!

**Comment by budde377** [comment]
You're right, it doesn't support that yet. It shouldn't be that hard to implement though. What is your use case?

**Comment by kvinsu** [comment]
> You're right, it doesn't support that yet. It shouldn't be that hard to implement though. What is your use case?

I am using this library in a project with a complex database, therefore, for better maintenance and structure, I split the schemas into multiple smaller `.graphl`-files and used `extend` for additional queries and mutations.

**Comment by budde377** [comment]
I have a small backlog of issues I want to address this week or on the weekend. I'll try to get to this

**Comment by kvinsu** [comment]
That would be amazing, thanks!
