### ISSUE TITLE
Cache parsedData

### ISSUE THREAD

**Issue by sandrocsimas** [heftapp/graphql_codegen#263]
Couldn't we cache `parsedData`? Every time we get this attribute, the parser function is called. Even when there is no change to the data.
````
  /// If a parserFn is provided, this getter can be used to fetch the parsed data.
  TParsed? get parsedData {
    final data = this.data;
    final parserFn = this.parserFn;

    if (data == null) {
      return null;
    }
    return parserFn(data);
  }
````

**Comment by budde377** [comment]
Sound like a good improvement that should probably be raised in the GraphQL flutter package.

**Comment by sandrocsimas** [comment]
You're right. Let me create it there.
