### ISSUE TITLE
Add support for `when` methods for switching over union types

### ISSUE THREAD

**Issue by samandmoore** [heftapp/graphql_codegen#273]
Hi! 

Thanks for this library. I have been exploring codegen solutions for adopting gql and I've found that I generally prefer the decisions of this library to that of others like ferry/artemis/etc. 

I particularly appreciate the ways in which the generated types are easy to work with and feel remarkably similar to `freezed` classes (e.g. copyWith and deep copyWith support). 

In that vein, I am wondering if you'd be open to adding support for `when`/`maybeWhen` methods to union type hierarchies? 

`ferry` recently added this feature in the last few months via `gql_code_builder` (https://github.com/gql-dart/gql/pull/377) if you're curious what it would look like.

Thanks again! 

Btw, I've never contributed to this library, but I'd be willing to try to add this feature if it's desired. I don't have a lot of experience working with codegen libraries, but I think with some pointers I could figure out how to add this.

**Comment by budde377** [comment]
I think this is a great idea!

**Comment by budde377** [comment]
Released as `v0.12.1`.

**Comment by samandmoore** [comment]
Thanks!
