### ISSUE TITLE
GQL 1.0.0 has been released

### ISSUE THREAD

**Issue by tjarvstrand** [heftapp/graphql_codegen#280]
Which means that `graphql_codegen` is not compatible with the latest version. Bummer that you just made a release :/

Thanks for a great package!

**Comment by budde377** [comment]
A PR is highly appreciated.

**Comment by tjarvstrand** [comment]
> A PR is highly appreciated.

I definitely don't mind spending some time to fix bugs in the libraries I use. However, as someone without any experience at all with the internals of this package in particular I don't really feel comfortable enough to take on a PR with such a huge potential impact on other users. 

Dependency management can be very complex and I definitely don't sit on enough information about the bigger picture of this library.

**Comment by budde377** [comment]
Up to you, but this is exactly why we have a review process and any change like this would never be your responsibility.

**Comment by budde377** [comment]
@vincenzopalazzo, do you mind creating a new release? Then we can update this package.

**Comment by vincenzopalazzo** [comment]
@budde377 I will do now :)
