### ISSUE TITLE
Two different queries returning the same type won't give the same name for that returned type

### ISSUE THREAD

**Issue by oyatrides** [heftapp/graphql_codegen#288]
Hello, 

I was using this package fine when I faced a big problem. Maybe I'm doing something wrong I don' t know, because I'm surprised that I didn't see this problem arise in existing issues.

Let's say I have 2 queries : 
getFriends : [Friends]
getAvailableFriends : [Friends]

However when using the generated type by this package, I will get Query$GetFriends$getFriends as a return type for the first query, and  Query$GetAvailableFriends$getAvailableFriends for the second (I called the queries GetFriends and GetAvailableFriends in the friends.graphql file).

This types have two differents names, but they represent the exact same Friends type from graphql. 
This causes me a problem when I try to use this two "different" types together as they're incompatible. 

I guess that a solution would be to do some kind of union type between the two generated types to a single one  would create : Friends. However I saw you can't do union in Dart. 

Is there something I'm doing wrong ? Maybe i'm not using this package right. 

Thank you for your help.

**Comment by oyatrides** [comment]
Alright I will test this, and I will get back to you as soon as possible to let you know if everything's fine. Thank you very much for your swift response.

**Comment by oyatrides** [comment]
I have another question that arose during the test about nested fragments.
So I have for example this schema : 

```
type User {
  username: String!
  email: String
  sex: Sex
  age: Int
  notifications: [Notification!]
}
union Notification = FriendRequestNotification | NewsNotification

type FriendRequestNotification {
  requesterUsername: String!
}

type NewsNotification {
  newsId: String!
}

type Query {
	getUser(username: String!): User
}
```

And I have these frontend queries : 

```
fragment FullFriendRequestNotification on FriendRequestNotification {
  requesterUsername
}

fragment FullNewsNotification on NewsNotification {
  newsId
}

fragment FullUser on User {
  username
  email
  sex
  age
  notifications {
    ...FullFriendRequestNotification
    ...FullNewsNotification
  }
}

query GetUser($username: String!) {
  getUser(username: $username) {
    ...FullUser
  }
}

query GetNotifications($username: String!) {
  getUser(username: $username) {
    __typename
    username
    notifications {
      ...FullFriendRequestNotification
      ...FullNewsNotification
    }
  }
```

When I do the query GetUser, here's what I get for the notification subType FriendRequestNotification : `Fragment$FullUser$notifications$$FriendRequestNotification
`
However, I expected something like that : `Fragment$FullFriendRequestNotification`

Because when I do GetNotifications, I will get this FullFriendRequestNotification subtype as well, and it brings me back to my first problem when creating this issue : I will have 2 different types for the same entity.

Is it an expected behavior or am I not using fragments right ?

Again, thank you for your help.

**Comment by budde377** [comment]
If you take a look at the generated code, you will notice that the `Fragment$FullUser$notifications$$FriendRequestNotification` class is implementing `Fragment$FullFriendRequestNotification`, so the type is both.
