### ISSUE TITLE
Feature Request - Query Schema Enums

### ISSUE THREAD

**Issue by yoodame** [heftapp/graphql_codegen#289]
I couldn't find evidence of this feature. Please advice if this is already possible.

It would be helpful to be able to generate enum queries like the following:

```graphql
query {
  __type(name: "CountryCode") {
    enumValues {
      name
      description
    }
  }
}
```

where `CountryCode` is defined in the schema as:

```graphql
"Country codes"
enum CountryCode {
  "Afghanistan"
  AF
  "Albania"
  AL
  "Algeria"
  DZ
  "American Samoa"
  AS
  ...
}
```

**Comment by budde377** [comment]
This seems like something your server needs to support?

**Comment by budde377** [comment]
Alright, I think I understand what you are raising. The newest release should support introspection on `__schema` and `__type`.

**Comment by yoodame** [comment]
@budde377 works beautifully. Cheers!
