### ISSUE TITLE
Take @deprecated annotation into account

### ISSUE THREAD

**Issue by subzero911** [heftapp/graphql_codegen#291]
Currently `graphql_codegen` doesn't care about @deprecated annotations.

I propose to mark deprecated fields as `@Deprecated` in Dart code, with the reason.

So this line in `.graphql` file
```graphql
    statuses: [TaskStatus!] @deprecated(reason: "Use filter.statuses instead.")
```

transforms into this:

```dart
   @Deprecated('Use filter.statuses instead.')
   final List<TaskStatus>? statuses;
```

Thanks to this, I'll immediately see obsolete API in IDE as strike through, with deprecation note.

**Comment by budde377** [comment]
Great suggestion. Released as `0.13.2`
