### ISSUE TITLE
Support default values

### ISSUE THREAD

**Issue by subzero911** [heftapp/graphql_codegen#293]
I have the following input type:
<img width="482" alt="image" src="https://github.com/heftapp/graphql_codegen/assets/12999702/54a261da-717f-4519-965c-c47b01dc8215">

**Expected result:** 
Codegen will use this default value.

**Actual result:**

- generated code:
<img width="542" alt="image" src="https://github.com/heftapp/graphql_codegen/assets/12999702/3a1cdeaf-1d49-4c33-95c6-31fc0f97958b">

- error:
<img width="787" alt="image" src="https://github.com/heftapp/graphql_codegen/assets/12999702/d4945aaa-38fc-421d-ad6f-b07a4c860057">

---
Codegen marks it as `required` and ignores `= true` part, but that's not correct.
It should generate `bool shouldSetupSubscription = true` instead.

**Comment by budde377** [comment]
I am not sure this is should be the expected behaviour. When you are making an argument required, you need to provide it in graphql, irrespectively of the presence of a default value. The logical approach for the code generator would be to follow the GraphQL behaviour, ie expecting people to provide this value.

**Comment by subzero911** [comment]
No, `!` mark means that it is "non-nullable", not "required"

And the default value works fine in Postman.

**Comment by subzero911** [comment]
The codegen logic should be the following:

For non-nullable (`Boolean!`):
It checks if there is a default value in the schema (`= true`).
- If no -> generate `required bool myValue`
- If yes -> generate `bool myValue = true`

For nullables (`Boolean`):
It checks if there is a default value in the schema.
- if no -> generate `bool? myValue`
- if yes -> generate `bool? myValue = true`

**Comment by budde377** [comment]
Thank you for your suggestion. I'll take a second look and see if I agree

**Comment by budde377** [comment]
You are correct that the only required input is non-nullable without a default value, but re-producing the default value in the code-generator is not valid because we will lose expressiveness, e.g., we will not be able to communicate that an input value was not provided. 

Instead, we need to handle the case when a non-null input has a default value, which is done in #294.

**Comment by subzero911** [comment]
How would it work?

**Comment by budde377** [comment]
Try out `graphql_codegen: ^0.13.3` to see how it will work on your example.

**Comment by subzero911** [comment]
@budde377 it now generates nullable `bool?` despite in schema it's defined as `Boolean!`
<img width="512" alt="image" src="https://github.com/heftapp/graphql_codegen/assets/12999702/5b41f3d1-4221-45a1-bae1-f553dd4963d9">

Also, there's now a new error in another file:
<img width="904" alt="image" src="https://github.com/heftapp/graphql_codegen/assets/12999702/b5b3f6b1-9974-44e8-9648-c8c788ad74eb">

**Comment by subzero911** [comment]
Source schema is 
<img width="373" alt="image" src="https://github.com/heftapp/graphql_codegen/assets/12999702/dbe7436e-eedb-4cd5-b0c7-93308c06d782">
<img width="222" alt="image" src="https://github.com/heftapp/graphql_codegen/assets/12999702/20e0eb8c-0761-455a-b027-ce9a02fa5a59">

And resulting nullable `Enum_ColorMode?` doesn't fit into the method's argument.
<img width="452" alt="image" src="https://github.com/heftapp/graphql_codegen/assets/12999702/9529db84-69ad-4772-a7f1-0687f87a85ef">

**Comment by budde377** [comment]
>  it now generates nullable bool? despite in schema it's defined as Boolean!

This is expected. If the value is omitted, it will not be sent.

> Also, there's now a new error in another file:

This is not expected and should be fixed in #295

**Comment by subzero911** [comment]
Generating nullable for non-nullable field, while still ignoring the default value, is even worse 😟

**Comment by budde377** [comment]
But we are not ignoring the default value. The default value is handled by the server.

**Comment by budde377** [comment]
Try `graphql_codegen: ^0.13.4` and see if it works for you.

**Comment by subzero911** [comment]
> But we are not ignoring the default value. The default value is handled by the server.

It generates   <img width="326" alt="image" src="https://github.com/heftapp/graphql_codegen/assets/12999702/88fb20da-c371-4b65-910d-b103b7794d28">
Which is null by default

While it's defined in schema: 
<img width="391" alt="image" src="https://github.com/heftapp/graphql_codegen/assets/12999702/4253d50c-e7fc-41d7-9c98-962e3491144c">

**Comment by budde377** [comment]
This is only to say that the value isn't required. If you don't provide it, it isn't going to send `null` to your server. Your server should substitute the missing value with the default value defined on the schema.

**Comment by subzero911** [comment]
So you basically just moved default value handling to the server.
Now it has to both define the default value in schema and handle it if I send the null.

**Comment by budde377** [comment]
It won't send `null` to your server

**Comment by budde377** [comment]
Please try it out and let me know if it doesn't work as expected.

**Comment by subzero911** [comment]
It makes sense 🤔
So I shouldn't bother about default values and look into schemes.

**Comment by budde377** [comment]
> So I shouldn't bother about default values and look into generated code.

I am not sure what you mean.

**Comment by subzero911** [comment]
Yes, I asked our backender, and he confirmed, that if I don't provide the value, server will substitute it with the default one from the schema.
So I'm satisfied with the current solution.
