### ISSUE TITLE
`.graphqls` file support

### ISSUE THREAD

**Issue by kikuchy** [heftapp/graphql_codegen#306]
Thank you for developing awesome libraries!

Our team is considering to use graphql_codegen for new Flutter application.
And the server side application already have GraphQL scheme definitions as `.graphqls` files.
Current graphql_codegen doesn't support `.graphqls` files, we have to copy and rename `.graphqls` files to `.graphql` and have to sync it manually.
It's perfect for us if graphql_codegen supports .graphqls` files, so we hope it.

Is there any plans to support `.graphqls` files? Thank you!

**Comment by budde377** [comment]
Im sure we can accommodate this
