### ISSUE TITLE
code_gen takes about 4 minutes to generate with even just small change in one query

### ISSUE THREAD

**Issue by Puciek** [heftapp/graphql_codegen#311]
Heya,

We have a project with gql schema that's already notable and growing (1k+ lines and lots of queries in the code), and every time we run `dart run build_runner build` it takes about 4 minutes to finish. Which would be less of an issue if we were talking about updates on schema, but we also must run it when adjusting queries, which as you can imagine is quite cumbersome on development.

Are we doing something wrong? Is there something where we can tweak this? Realistically for something we must run at every query change, the time I would expect should be in seconds max, so minor tweaks is not what I am after here, just more hoping we've messed something up badly.

**Comment by budde377** [comment]
Thanks for raising your issue, what version are you on?

**Comment by Puciek** [comment]
0.13.1

**Comment by budde377** [comment]
I am very surprised you are seeing such poor performance. If you are able to share your schema and queries, e.g. in private repo, then I can try and run the generator against it and identify any bottlenecks.

**Comment by Puciek** [comment]
Sure, i'll get some examples sorted for you later today, thank you :D
