### ISSUE TITLE
Problems with hasura relay api

### ISSUE THREAD

**Issue by erik-seifert** [heftapp/graphql_codegen#314]
I try to call hasura relay api endpoint and get the following error.

`GraphQLError(message: field 'event_connection' not found in type: 'query_root', locations: null, path: null, extensions: {path: $.selectionSet.event_connection, code: validation-failed})`

Query:

```
query GetEvent {
  event_connection {
    edges {
      cursor,
      node {
        title
        created_at
        description
      }
    }
  }
}
```

But is see in schema

```
type query_root {
 ....
  """
  fetch data from the table: "event"
  """
  event_connection(
    after: String
    before: String

    """distinct select on columns"""
    distinct_on: [event_select_column!]
    first: Int
    last: Int

    """sort the rows by one or more columns"""
    order_by: [event_order_by!]

    """filter the rows returned"""
    where: event_bool_exp
  ): eventConnection!
 ....
}
```

**Comment by budde377** [comment]
This looks like a runtime error, so it would seem that your endpoint doesn't agree with the schema. It doesn't look like an error in the code generator

**Comment by erik-seifert** [comment]
If i try to call this query directly on (on graphql explorer) everything works like expected.

**Comment by erik-seifert** [comment]
Do not work to late. Found it. Thx for your help.

**Comment by erik-seifert** [comment]
And thanks for the great library.
