### ISSUE TITLE
Trouble Getting Started

### ISSUE THREAD

**Issue by Nexushunter** [heftapp/graphql_codegen#318]
I'm working with the getting started and I'm unable to generate the dart code from the schema. 

My  build yaml config:
```yaml
targets:
  $default:
    builders:
      graphql_codegen:
        options:
          # Remove the $ from the class names
          namingSeparator: ""
          generatedFileHeader: "// GENERATED FILE DO NO MODIFY BY HAND\n"
          outputDirectory: /lib/graphql
          assetsPath: /graphql/**
          clients: 
            - graphql_flutter
```
I have a `schema.graphql` located within `/graphql/`.

My pubsec looks like:
```yaml
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  graphql: ^5.1.3
  graphql_flutter: ^5.1.2
  flutter_hooks: ^0.20.3

dev_dependencies:
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  graphql_codegen: ^0.13.7
```

The following statement in the readme was uninformative:
> Read more about the tool and motivation at the [GraphQL Codegen deep-dive](https://budde377.medium.com/graphql-codegen-deep-dive-37eee522e4e5) and on how you can structure your flutter apps with the tool on [Structure your Flutter GraphQL apps](https://budde377.medium.com/structure-your-flutter-graphql-apps-717ab9e46a5d).
> The framework does not fetch your schema for you, so before you run this, you'll need to add your schema to your project. In Android Studio this can be done with the [GraphQL](https://plugins.jetbrains.com/plugin/8097-graphql) plugin.

I'm using vscode as my IDE and my flutter env looks like:
```
Flutter 3.13.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 6c4930c4ac (4 weeks ago) • 2023-10-18 10:57:55 -0500
Engine • revision 767d8c75e8
Tools • Dart 3.1.4 • DevTools 2.25.0
```

Running `dart run build_runner build` produces:
```
[INFO] Generating build script completed, took 273ms
[WARNING] Throwing away cached asset graph because the build phases have changed. This most commonly would happen as a result of adding a new dependency or updating your dependencies.
[INFO] Cleaning up outputs from previous builds. completed, took 6ms
[INFO] Generating build script completed, took 52ms
[WARNING] Invalidated precompiled build script due to missing asset graph.
[INFO] Precompiling build script... completed, took 639ms
[INFO] Building new asset graph completed, took 763ms
[INFO] Checking for unexpected pre-existing outputs. completed, took 0ms
[INFO] Running build completed, took 3ms
[INFO] Caching finalized dependency graph completed, took 63ms
[INFO] Succeeded after 73ms with 0 outputs (0 actions)
```

Is there additional configuration that I am missing?

**Comment by budde377** [comment]
Thanks for reporting @Nexushunter! A bug here prevents finding GraphQL files in the `graphql` folder (it works for any sub-folder of `graphql`). I've fixed this in #319. 

Remember to add `graphql` in your [sources options](https://github.com/dart-lang/build/blob/master/docs/faq.md#how-can-i-include-additional-sources-in-my-build)
