### ISSUE TITLE
Have auto-generated files pass dart analyzer cleanly

### ISSUE THREAD

**Issue by klondikedragon** [heftapp/graphql_codegen#32]
The official dart extension for vscode (and maybe other IDEs?) will only do auto-completion as you type for dart types that are included in the dart analyzer. If they are excluded from the dart analyzer, if you do type the full/correct type name, then it does recognize it still. However, since the auto-generated type names can be quite long, it's more productive to have these auto-completed. And currently if you do not exclude the auto-generated code from the analyzer, it adds lots of warnings to the IDE's list of problems (which I strive to keep at zero).

For the auto-generated files to pass the analyzer without adding warnings, the following could be generated at the top of each auto-generated file:
```
// ignore_for_file: constant_identifier_names, unnecessary_const
// ignore_for_file: unnecessary_this, annotate_overrides
```

(The code gen could be adjusted to fix the root cause of all but the first one of these; changing the identifier name pattern would be a breaking change and I personally like the auto-generated constants as they are (all upper separated by underscores)).

What do you think?

(P.S. thanks for adding client codegen for subscriptions, and for the query parseFn! those are working beautifully!!)

**Comment by budde377** [comment]
I appreciate your descriptive issues and solutions and am happy that the changes works!

I'm curious if this is related to the analyzer version which is lacking behind on `gql` and thereby on this project, which version are you using? 

Regardless, I think there's a case for stronger customization of the generated files, so we can alleviate issues like this in the future. Quick question, what happens if I ignore an issue that isn't present in the file? E.g.,


```
// ignore_for_file: unnecessary_this
```

and there's no unnecessary this. Is this an error in itself?

**Comment by klondikedragon** [comment]
It's true I was using an explicit override of the analyzer dev-dependency to an older version (2.8.0) because I'm using several different code-gen packages in addition to this one (fast_i18n, freezed, json_serializable, stacked_generator) and it wouldn't resolve by itself. I forced the analyzer to the latest version (3.2.0) and it raised the same analyzer warnings on the auto-generated files though.

Based on testing, it looks like it's not an error itself to ignore an issue that isn't present in the file. So it wouldn't have to determine if the issue existed in the auto-generated file based on which artifacts were generated, only put that constant comment block somewhere in the file and it should be good. As an aside, it also doesn't appear to be an issue to ignore a warning type that isn't (yet) known, e.g., `ignore_for_file: foo_bar` is not an error either.

**Comment by budde377** [comment]
You can now provide custom headers to all generated files through the `generatedFileHeader` build config, which I believe should do the trick!

**Comment by klondikedragon** [comment]
This works beautifully, thank you! It may be good to document that users will likely want to include a newline `\n` at the end of the generatedFileHeader value, otherwise the generated dart won't compile.

For reference, here is the build.xml config value I'm now using and my generated files have no more analyzer warnings.
```
generatedFileHeader: "// ignore_for_file: constant_identifier_names, unnecessary_const\n// ignore_for_file: unnecessary_this, annotate_overrides\n\n"
```

Thanks again!

**Comment by Aristidios** [comment]
If it can help someone here are the rules I had to ignore in my generated files 

```
// ignore_for_file: implicit_dynamic_map_literal
// ignore_for_file: implicit_dynamic_parameter
```

add them through the `generatedFileHeader:` under `options:` in your build.yaml file 🙂
