### ISSUE TITLE
`Invalid GraphQL: Failed to find type for field` for extended query and same name nesting fields

### ISSUE THREAD

**Issue by kikuchy** [heftapp/graphql_codegen#331]
Thank you for really useful package! Our team is using this very conveniently.

We found one problem, the extended type's query with same name nested response causes build_runner error.

Env:
```
  graphql_codegen: 0.13.10
  build_runner: 2.4.7
```

Code:
```query.graphql
# query.graphql
type Query {
}

# (1)
extend type Query {
    foo: FooResponse!
}

type FooResponse {
    foo: FooCore!
}

type FooCore {
    bar: String!
}

query FooQuery {
    foo {
        # (2)
        foo {
            # (3)
            bar
        }
    }
}
```

Result:
```
$ flutter pub run build_runner build
Deprecated. Use `dart run` instead.
[INFO] Generating build script completed, took 194ms
[INFO] Reading cached asset graph completed, took 54ms
[INFO] Checking for updates since last build completed, took 754ms
[SEVERE] graphql_codegen on lib/query.graphql:

Invalid GraphQL: Failed to find type for field bar on FooResponse
[INFO] Running build completed, took 52ms
[INFO] Caching finalized dependency graph completed, took 37ms
```

We have tried to reproduce the error and found 3 points.

1. It needs `extend` for `Query`
    * It doesn't reproduce the error if `Query.foo` is defined in `Query` directly.
2. needs nesting same name fields
    * It also doesn't reproduce the error if second `foo` (`FooResponse.foo`) is different name.
3. needs *non `foo`* filed name for inside of second `foo`
    * It also doesn't reproduce the error if using `foo` (`FooCore.foo`) instead of `bar` (`FooCore.bar`).

We are using `extend` to separate huge query files and already defined same name nesting fields for non-flutter platforms.

we hope this problem fixed. Thank you!

**Comment by budde377** [comment]
Thanks for reporting this issue. A fix should be published as `0.13.11`!

**Comment by kikuchy** [comment]
Thank you for extremely fast fixing!! We really appreciate!

**Comment by budde377** [comment]
No worries mate! Thanks for  providing the example.
