### ISSUE TITLE
Add the option to skip a query when using hooks

### ISSUE THREAD

**Issue by davidgtu** [heftapp/graphql_codegen#345]
First off, thank you for making this library. As a long-time React developer and using graphql + codegen there, the introduction of `useQuery` hooks has made my developer experience so much smoother.

One thing I found helpful when using the generated `useQuery` hooks on the web side is that we have the option to skip a query. [Here's the documentation on Apollo on its usage.](https://www.apollographql.com/docs/react/data/queries/#queryhookoptions-interface-skip)

I'm using a hook that looks like this, all generated from this library:

```dart
final fetchChallengeDetailQuery = useQuery$FetchChallengeDetails(
  Options$Query$FetchChallengeDetails(
    fetchPolicy: FetchPolicy.networkOnly,
    variables: Variables$Query$FetchChallengeDetails(
      id: challengeId,
    ),
  ),
);
```

However, `challengeId` is type `String?` and `id` is looking for `String`. If I were to implement this in React, having the ability to `skip` the query if `challengeId` is null would help with compiling and error catching. I feel that this might be a good addition to this library. I would propose to add an optional field under `options`

```dart
final fetchChallengeDetailQuery = useQuery$FetchChallengeDetails(
  Options$Query$FetchChallengeDetails(
    skip: !challengeId,
    fetchPolicy: FetchPolicy.networkOnly,
    variables: Variables$Query$FetchChallengeDetails(
      id: challengeId,
    ),
  ),
);
```

So the hook wouldn't run if `skip` was true. 

I would love to know your thoughts!

**Comment by budde377** [comment]
Thank you for creating this issue @davidgtu. I think the right approach would be to add this to the underlying [GraphQL Flutter client](https://github.com/zino-hofmann/graphql-flutter) and then add it here. In the mean time, have you tried the `@skip` directive?
