### ISSUE TITLE
Option to disable CopyWith generation

### ISSUE THREAD

**Issue by sigis151** [heftapp/graphql_codegen#352]
is there abitily to disable CopyWith methods generation to reduce generation time?

**Comment by budde377** [comment]
Thanks for reaching out @sigis151 - before we consider this, I would like to understand your setup better. What kind of generation times are you seeing and how many GraphQL files are you generating?

**Comment by sigis151** [comment]
Hi,
we have around ±100 different queries in the project and it can take up to a minute to rebuild (`dart run build_runner build --delete-conflicting-outputs`) all generated files, and as we re-map all gql responses to our own domain classes I don't see any real need for copy methods that are generated :)

**Comment by budde377** [comment]
I've added the `disableCopyWithGeneration`. Setting this to `true` will disable copy-with generation.

**Comment by budde377** [comment]
Those should be added back again in `1.0.1`.

**Comment by orestesgaolin** [comment]
Thanks, about 100k lines of generated Dart code removed!
