### ISSUE TITLE
Support for the @oneOf directive

### ISSUE THREAD

**Issue by tjarvstrand** [heftapp/graphql_codegen#354]
The [RFC for the new @oneOf directive](https://github.com/graphql/graphql-spec/pull/825) is now basically just a formality away from being accepted into the GraphQL spec.

It would be great to see type level support for it in `graphql_codegen`.

BTW, thanks for an awesome library!

**Comment by budde377** [comment]
`@oneOf` should now generate different factories for each field. Please check it out and let me know what you think.
