### ISSUE TITLE
access the query/mutation string from the generated class

### ISSUE THREAD

**Issue by Yakiyo** [heftapp/graphql_codegen#370]
Hi, ive been tinkering on a simple flutter app for a few days which uses data from an external graphql api. The api itself is huge and using graphql_codegen is really handy for me. While im getting the classes generated by the package, i have no way of accessing the query string itself. 
Lets say i have a graphql file as such
```graphql
fragment MediaMinimalFrag on Media {
  id
  type
  title {
    romaji
    userPreferred
  }
  coverImage {
    large
    medium
  }
}

query MediaMinimal($id: Int, $search: String) {
  Media(id: $id, search: $search) {
    ...MediaMinimalFrag
  }
}

query MediaFull($id: Int, $search: String) {
  Media(id: $id, search: $search) {
    ...MediaMinimalFrag
    nextEpisode
    // other fields here
  }
}
```
while graphql_codegen is generating appropiate classes for me, i do not have any way of accessing the query i need, for example the MediaFull or MediaMinimal query in my dart code. I do not want to go through the hassle of using graphql/graphql_flutter as those are overkill for my app, since having stuff like caching and others are more of an issue for me. So i do not have access to the query in runtime, i could probably hard code the .graphql file's content to some variable at build time but in that case, since each of my files contain multiple queries/mutations together, i cannot execute a single query (at least i do not know of any method). I just want to have access to the query as a string or something so that i can use the [http](https://pub.dev/packages/http) to execute requests. Like the MediaFull query, would have a class Query$MediaFull with a static method or getter that returns the query in string format or something similar.

The only solution i can think of rn is to split my queries all in individual files, read the files to variables at compile time and use them.

**Comment by Yakiyo** [comment]
I found out about the [`operationName`](https://graphql.org/learn/serving-over-http/#post-request-and-body) field which allows me to execute only one query/mutation from an entire file but even then i'd have to make a build script for build_runner that writes the .graphql files into string variables in a dart file. All in all, having access to a query/mutation from its corresponding class would be a good option for using with packages like http or other http packages maybe? im not really the most knowledgable about graphql related stuff so it might just be a me case

**Comment by budde377** [comment]
Hi @Yakiyo, thanks for reaching out. 

Take a look at this PR which illustrates how you can print your query from the generated `documentNodeX`: https://github.com/heftapp/graphql_codegen/pull/371/files#diff-f0e54447ce559e84afda2fbe069cc30bab59f6c5b943da9ce195cf801f2b43ee.

Let me know if this answers your question.

**Comment by Yakiyo** [comment]
@budde377 thank you so so much. That example was really clear and it really helped me. Really appreciate the quick response and help. Ty very much for the help.
