### ISSUE TITLE
Improve compatibility with Dart’s is! operator

### ISSUE THREAD

**Issue by mohagali** [heftapp/graphql_codegen#372]
I’m using the GraphQL code generator in Flutter, and VS Code shows this warning:

`Use the 'is!' operator rather than negating the value of the 'is' operator. Try rewriting the condition to use the 'is!' operator.dartprefer_is_not_operator
`

It suggests rewriting conditions to use is! instead of !(is) for better readability and code quality. It would be great if the generated code could follow this guideline.

**Comment by budde377** [comment]
Should be easy enough. A pr is always appreciated. 🙂

**Comment by budde377** [comment]
Thanks!
