### ISSUE TITLE
feature request: Exposing Union Types __typename cases

### ISSUE THREAD

**Issue by manlyman29** [heftapp/graphql_codegen#377]
Exposing union type's different possible values for` __typename` can be especially useful for creating fake implementations of fragments for development environments. If these possible values were accessible from `UtilExtensions` through an enum, it could ensure type safety of fragment fake classes, preventing potential issues if the backend's union type definition changes.

**Comment by budde377** [comment]
I am not completely sure what you are asking. Please elaborate with examples for my understanding.

**Comment by manlyman29** [comment]
I was trying to create instances of Union types without having to pass __typename in string. I just found out this is possible through Fragment$[Union Type]$$[Type Case] class. It's resolved, thanks.
