### ISSUE TITLE
Not provided optional values are returned as `null` in mutation

### ISSUE THREAD

**Issue by jhlabs** [heftapp/graphql_codegen#46]
First of all thanks for this great library. I am migrating my Graphql code from the `ferry` package right now and the generated code here is a lot more straightforward and reusable.

I have the following mutation:

```graphql
mutation CreateEmailInvites($invites: [invites_insert_input!]!) {
  insert_invites(objects: $invites) {
    returning {
      id
    }
  }
}
```

and using it with the generated client code for the `graphql` package like so:

```dart
_client.watchMutationCreateEmailInvites(
            GQLWatchOptionsMutationCreateEmailInvites(
              eagerlyFetchResults: true,
              variables: VariablesMutationCreateEmailInvites(
                invites: inviteInputs
                    .map(
                      (invite) => InputinvitesInsertInput(
                        inviteCode: invite.inviteCode,
                        email: invite.email,
                        inviterId: invite.inviterId,
                        name: invite.name,
                      ),
                    )
                    .toList(),
              ),
            ),
          )
```

Now the issue is that the `Invites` model in my graphql API has additional optional values that I am not passing along, but instead of omitting them the generated payload in the final request sets them to `null`:

```json
{
  "operationName": null,
  "variables": {
    "invites": [
      {
        "created_at": null,
        "email":  "test@test.co",
        "id": null,
        "invite_code": "VIMtrBLA40",
        "invitee_id": null,
        "inviter_id": "886f91c3-4162-4391-a187-7cad9c9b666d",
        "name": "Johannes",
        "profile": null,
        "status": null
      }
    ]
  },
  "query": "mutation CreateEmailInvites($invites: [invites_insert_input!]!) {\n  insert_invites(objects: $invites) {\n    returning {\n      id\n      __typename\n    }\n    __typename\n  }\n  __typename\n}"
}
```

My graphql server rejects this request as `null` values are not allowed on these fields.

How can one send a partial insert or update request without including other fields as null values? Thanks a lot for your help.

**Comment by budde377** [comment]
Thanks for reaching out. This is interesting, I'm very surprised about the servers handling of this, but I think I understand the use case. Let me have a look and a think, as a quick fix you might be able to extend the variables class  and overwrite the serialisation with a custom implementation?

**Comment by jhlabs** [comment]
@budde377 thanks a lot! Using modifying the `json_serializable` setting fixed this issue. I am using Hasura as a GraphQL backend server.  Hasura does not accept `null` values as such.

**Comment by aquadesk** [comment]
I encounter the same issue with Strapi v4 graphql backend!!
Thanks for the workaround guys!

Saved my day.

**Comment by budde377** [comment]
Due to issues with serialization of cache methods, there's a new option to only strip fields containing `null` from input serializers.

https://github.com/heftapp/graphql_codegen/tree/main/packages/graphql_codegen#strip-null-from-input-serializers
