### ISSUE TITLE
Multiple graphql schema

### ISSUE THREAD

**Issue by dioseltorre** [heftapp/graphql_codegen#48]
Does this library supports multiple schema?
I have a case in which the app uses two gql schemas (e.g. `test1.schema.graphql`, `test2.schema.graphql`) for two different endpoints.

**Comment by budde377** [comment]
The library requires you to fetch the schema and store it locally. It then assumes that the queries are relative to this. 

There's currently no good way of specifying that some queries are relative to a schema and some to others. So no support for multiple schemas. 

Do you have any thoughts on how we could solve your use case? How are you structuring your project?

**Comment by budde377** [comment]
I've implemented a feature to support multiple schemas. Read more [here](https://github.com/heftapp/graphql_codegen/tree/main/packages/graphql_codegen#multiple-schemas).

**Comment by dioseltorre** [comment]
@budde377 When do you plan to release this?

**Comment by budde377** [comment]
@dioseltorre, it should already be released in the latest beta 😄

**Comment by karthik-js** [comment]
@budde377 I have a question regarding scopes parsing the appropriate assets files. How does the library choose the schema files to parse assets appropriately?

**Comment by budde377** [comment]
@karthik-js the library doesn't distinguish between schemas and operations. So you'll need to make sure that you've downloaded your schema and put it in the appropriate scope.
