### ISSUE TITLE
How can we remove the unset field (null) from request body before sending the request?

### ISSUE THREAD

**Issue by lodisy** [heftapp/graphql_codegen#62]
For example,

I have a query function: 

```
  // get users

  Future<List<User>> getUsers({VariablesQueryUsers? variables}) async {
    final _result =
        await client.queryUsers(OptionsQueryUsers(variables: variables));

    if (_result.hasException) throw _result.exception!;

    final _users = QueryUsers.fromJson(_result.data!).users;

    return _users
        .map(
          (_user) => User.fromJson(_user.toJson()),
        )
        .toList();
  }
```

`VariablesQueryUsers`:

```
class VariablesQueryUsers extends JsonSerializable {
  VariablesQueryUsers(
      {this.where,
      this.orderBy,
      this.cursor,
      this.take,
      this.skip,
      this.distinct});
...
```
and these fields can be optional, thus all set to null.

when sending request with this:

```
_repository
        .getUsers(
          variables: VariablesQueryUsers(
            orderBy: [
              InputUserOrderByWithRelationInput(
                createdAt: EnumSortOrder.desc,
              )
            ],
            take: 10,
          ),
        )
```

Here I only set the `orderBy` and `take`, the request body contains all other fields that contain null, which throw the error as my backend doesn't support that. Maybe I missed something, but I am wondering if I can transform the request body before sending it.

![Screenshot 2022-04-02 at 20 31 03](https://user-images.githubusercontent.com/8101584/161398760-2b494ca9-e4fc-41af-b4c0-d8ec85562ab3.jpg)

**Comment by budde377** [comment]
I think this is the same case as #46?

**Comment by lodisy** [comment]
> I think this is the same case as #46? 

Yes exactly thank you!
