### ISSUE TITLE
Why extend `JsonSerializable`?

### ISSUE THREAD

**Issue by mernen** [heftapp/graphql_codegen#67]
Hi, I've noticed that all classes that have the `@JsonSerializable()` metadata (whether they are part of the repository or generated) extend `JsonSerializable`. Why is that? As far as I know, this is only adding a few weird properties to every object, like `fieldRename`. It's not a requirement of `json_serializable`.

**Comment by budde377** [comment]
Good catch. You're right, there doesn't seem to be any reason for this. I've removed it in `0.7.2`
