### ISSUE TITLE
Support new callbacks on query options

### ISSUE THREAD

**Issue by budde377** [heftapp/graphql_codegen#69]
https://github.com/zino-hofmann/graphql-flutter/pull/1097 adds two new callbacks to the `QueryOptions`, these should be generated the same way as `onCompleted` is on `MutationOptions`.

**Comment by tchala120** [comment]
Is there anything update for this issue? Thanks btw.

**Comment by budde377** [comment]
Thanks for reaching out! I hope to get this done very soon. A PR is always appreciated m.

**Comment by budde377** [comment]
Finally out!
