### ISSUE TITLE
Operations, type and input names ending with "_" creates duplicate definitions in generate dart files

### ISSUE THREAD

**Issue by jorg1piano** [heftapp/graphql_codegen#73]
Two types with the similar names are converted to the same class name creating duplicate definitions:
Given a graphql schema of:
`input SongInput_ {...`
and 
`input SongInput {...`

Results in duplicate definitions in the generated *.graphql.dart file
`class InputSongInput {`
`class InputSongInput {`

**Comment by budde377** [comment]
Great catch, thanks for reporting! Let me have a think about the best approach to address this issue.
