### ISSUE TITLE
Mutation question

### ISSUE THREAD

**Issue by vasil-boshnyakov** [heftapp/graphql_codegen#77]
Hello,

first of all thanks for the great package! It's priceless!

I have the following schema:

```
type Query {
	listProducts(limit: Int, nextToken: String): ProductsConnection!
}

type Product {
	id: ID!
	title: String!
	content: String!
}

type ProductsConnection {
	items: [Product!]
	nextToken: String
}

type Mutation {
	createProduct(input: CreateProductInput!): Product!
}

input CreateProductInput {
	title: String!
	content: String!
}
```

How to build and pass the "CreateProductInput" to the mutation request? 
It's fine with the atomic types (int, String etc.). Can't get it working with Input objects.

Thanks!

**Comment by budde377** [comment]
Thanks for reaching out! The input should be generated in the dart file associated to your schema. I.e., if your schema is `schema.graphql` the `schema.graphql.dart` file should contain the class for inputs. See this test as an example: https://github.com/heftapp/graphql_codegen/blob/main/packages/graphql_codegen/test/assets/input/input.graphql.dart

**Comment by vasil-boshnyakov** [comment]
Great, thank you!
