### ISSUE TITLE
Generator not generates type objects, only enums and input

### ISSUE THREAD

**Issue by westito** [heftapp/graphql_codegen#83]
The generator finds graphql file, `.g` files are generated, but only contains enums and input types. 
I tried debug the generator. I see types in graphql parsed as `ObjectTypeDefinitionNode` but `ContextVisitor` not implements `visitObjectTypeDefinitionNode()` for that.

<img width="582" alt="Képernyőfotó 2022-05-24 - 14 45 03" src="https://user-images.githubusercontent.com/536799/170037785-b2782def-37f3-4a0b-aea5-c0333d74d872.png">
<img width="518" alt="Képernyőfotó 2022-05-24 - 14 44 23" src="https://user-images.githubusercontent.com/536799/170037787-7fc34871-609e-4e2d-9cbd-a32d9ec4c140.png">

**Comment by budde377** [comment]
Can you share your build.yaml file and your project structure?

**Comment by westito** [comment]
Sure
```yaml
targets:
  $default:
    builders:
      graphql_codegen:
        options:
          assetsPath: lib/gen/**.graphql
          clients:
            - graphql
```
```
├── CHANGELOG.md
├── README.md
├── analysis_options.yaml
├── android
...
├── build.yaml
├── generate.sh
├── ios
...
├── lib
│   ├── application
│   │   ├── init_app.dart
│   │   └── app.dart
│   ├── datasource
│   │   ├── data_controller.dart
│   │   ├── data_repository.dart
│   │   ├── data_service.dart
│   │   ├── data_service_cache.dart
│   │   ├── data_service_process.dart
│   │   ├── data_service_queries.dart
│   │   ├── data_service_subscriptions.dart
│   │   ├── endpoint_configuration.dart
│   │   ├── isolated_graphql.dart
│   │   └── mock_service.dart
│   ├── gen
│   │   ├── assets.gen.dart
│   │   ├── schema.graphql
│   │   └── schema.graphql.g.dart
│   ├── generated_plugin_registrant.dart
│   ├── main.dart
│   ├── models_sample
│   │   ├── match.dart
│   │   └── team.dart
│   ├── ui
│   │   └── pages
│   │       ├── home_page.dart
│   │       └── init_page.dart
│   ├── utils
│   │   ├── asset_reader.dart
│   │   ├── json_map.dart
│   │   ├── load_state.dart
│   │   ├── shared_pref.dart
│   │   ├── toast.dart
│   │   └── type_safe_casting.dart
│   └── widgetbook
│       ├── widgetbook_main.dart
│       ├── widgetbook_main.widgetbook.dart
│       └── widgets
│           └── test.dart
├── pubspec.lock
├── pubspec.yaml
├── test
```

**Comment by budde377** [comment]
Okay, got you. It looks like the generator is correctly generating serialisers for your schema. It does not generate serialisers for `type`, interfaces, or unions. This is by design. Why do you need these?

**Comment by syssam** [comment]
@budde377 
I have "type user", and have a schema query followers, and query following, they also return user type.
followers generated Query$UserFollowers$user$followers$edges$node.
however, on the widget, they should be the same type of followers, following, user
Do you have any suggestions to solve this issue?

**Comment by budde377** [comment]
They aren't, because you're querying different fields. You can express a common shape with a fragment which will give you a common interface
