### ISSUE TITLE
Docs do not reflect generated class names

### ISSUE THREAD

**Issue by masseelch** [heftapp/graphql_codegen#91]
When generating for a query like in the docs: 

```gql
# person.graphql

query FetchPerson($id: ID!) {
  fetch_person(id: $id) {
    name: full_name
  }
}
```

the example states the generated widget is named `Query$FetchPerson` while it is named `Query$FetchPersonWidget` instead. This led for me to nearly throw out this package, since it "did not work".

But it DOES works great, once one finds out this.

**Comment by budde377** [comment]
Thanks for reporting this! A pr is always highly appreciated!
