### ISSUE TITLE
Generator always generates exact types instead of interfaces

### ISSUE THREAD

**Issue by szantogab** [heftapp/graphql_codegen#92]
In this example, a Condition is an interface. There are many implementations for it. Like `AndCondition`, `OrCondition`, `TimeCondition`, etc.

On top of that, `AndCondition ` has left and right fields that are also `Condition`s.

Unfortunately, the generator currently generates FragmentAndCondition$left and FragmentAndCondition$right classes as you can see in the picture. However, I'd like it to use FragmentCondition classes instead here.

Is this currently possible?

<img width="422" alt="image" src="https://user-images.githubusercontent.com/2809091/172128500-7488da38-5965-4a07-9c22-142135a51cc0.png">

fragment Condition on Condition{
    type
}

fragment AndCondition on AndCondition{
    ...Condition
    left {
        ...Condition
    }
    right {
        ...Condition
    }
}

**Comment by budde377** [comment]
Thanks for creating this issue, the problem here is that we can't generally assume that the fragment interface is exactly matching the class for the field. You might be spreading multiple fragments or selecting additional fields, which will not be part of the `FragmentCondition`. What we can assume is that the field selection contains the fields from the fragment, which is why the selection (`FragmentAndCondition$left`) implements the `FragmentCondition`.

**Comment by szantogab** [comment]
Yes I understand, but the problem with this solution is that `FragmentAndCondition` or any implementation for that matter do not implement `FragmentAndCondition$left`. So I can't have a `TimeCondition` in the `left` field of the `AndCondition`.

Can't we somehow tell the generator that I want to generate a `FragmentCondition` class in place of `FragmentAndCondition$left`?

**Comment by budde377** [comment]
> Yes I understand, but the problem with this solution is that `FragmentAndCondition` or any implementation for that matter do not implement `FragmentAndCondition$left`. So I can't have a `TimeCondition` in the `left` field of the `AndCondition`.

What is a time condition and why is this a problem?

> Can't we somehow tell the generator that I want to generate a `FragmentCondition` class in place of `FragmentAndCondition$left`?


Because this would generally generate invalid code.

**Comment by szantogab** [comment]
`TimeCondition` was just an example. `TimeCondition` is an implementation of `Condition`. 

But because we have the `FragmentAndCondition$left left` in the `AndCondition`, I can't really say
`left = TimeCondition()` because `TimeCondition` is not a subclass of `FragmentAndCondition$left.` You see the problem?

**Comment by budde377** [comment]
> But because we have the `FragmentAndCondition$left left` in the `AndCondition`, I can't really say
`left = TimeCondition()` because `TimeCondition` is not a subclass of `FragmentAndCondition$left.` You see the problem?

I don't. Can you elaborate on why is this a problem?

**Comment by szantogab** [comment]
Because how do I put any `Condition` in the `left` or `right` fields? 

`left = TimeCondition(x, y)` will not work.
What I can do is a hack, by converting it with to and fromJson:
`FragmentAndCondition$left.fromJson(TimeCondition(x, y).toJson()).
`
Which kinda feels wrong. In the schema, the `left` and `right` fields are clearly of type `Condition`, and not of type `AndConditionLeft` or `AndConditionRight`. So the generator could know that oh the user only queries a `FragmentCondition` there, so it doesn't make sense to generate a new class called `FragmentAndCondition$left`, it can just use the existing `Condition` class.

Makes sense?

**Comment by budde377** [comment]
I understand that the classes don't match, but what I'm curious about is, why is this a problem? How are you using these classes? Before I can make such a significant change to the generated output, I'd love to have a better understanding of your use case.

**Comment by szantogab** [comment]
Sure, so as you know by now, I have a `Condition` class which represents a condition: and conditions, or conditions, not conditions, time condition, etc.

Therefore, the `Condition` class is abstract. Its implementations will determine how a `Condition` works.

This `Condition` class and its implementations are classes in my server code, and are exposed through the GraphQL schema.

Also, in my client code this generated `Condition` class is being used everywhere. I pass it around widgets, and then in the widget I can utilize polymorphism:

```
Widget _widgetForCondition(Condition condition) {
 if (condition is TimeCondition) return TimeConditionWidget(condition: condition);
 if (condition is AndCondition) return AndConditionWidget(condition: condition);
....
}
```

**This way, the client code is structured in the same way as on the server**, so when I make a change to a `Condition` instance, I can just send it to the server without having to cater for serialization, and deserialization.

**Comment by budde377** [comment]
Okay. So passing the condition to the client and using different fragments, e.g.

```graphql

fragment AndCondition on AndCondition {
  left { ... NonCompositeCondition }
  right { ... NonCompositeCondition }
}

fragment Condition on Condition {
  ...TimeCondition
  ...AndCondition
}

fragment NonCompositeCondition on Condition { 
  ...TimeCondition
}

fragment TimeCondition on TimeCondition {
  # Other fields
}
```

would allow you to do something like:


```dart
Widget _findWidget(FragmentCondition condition) {
    if (condition is FragmentAndCondition) return AndConditionWidget(condition: condition);
    if (condition is FragmentTimeCondition) return TimeConditionWidget(condition: condition):
}
```

This is possible now.

Can you go into more detail on what is currently not supported in your use case?

**Comment by budde377** [comment]
I've attached a PR with a more elaborate example of above. See how we can use them here: https://github.com/heftapp/graphql_codegen/pull/94/files#r891104116

**Comment by szantogab** [comment]
Sure, so if you were to have this query:

query conditions {
  conditions {
     ...Condition
  }
}

fragment AndCondition on AndCondition {
  left { ... Condition }
  right { ... Condition }
  ...Condition
}

fragment TimeCondition on TimeCondition {
  time
}

fragment Condition on Condition {
  __typename
 ...AndCondition
 ...TimeCondition
}

`final timeCondition = FragmentTimeCondition()`

you couldn't do this currently:
`final andCondition = FragmentAndCondition(left: timeCondition, right...)`

**because `left` is of type `FragmentAndCondition$left`, and not just simply `FragmentCondition`.**

Although in the query, we explicitly specify that our `left` and `right` fields are of type `FragmentCondition`, and nothing more.

**Comment by budde377** [comment]
This code is not valid GraphQL.

https://spec.graphql.org/October2021/#sec-Fragment-spreads-must-not-form-cycles

**Comment by szantogab** [comment]
I've modified my post, should be valid now.

**Comment by budde377** [comment]
> I've modified my post, should be valid now.

You still have cycles `Condition > AndCondition > Condition`

**Comment by szantogab** [comment]
> > I've modified my post, should be valid now.
> 
> You still have cycles `Condition > AndCondition > Condition`

This is how I have it currently and the server returns the response nicely.

**Comment by budde377** [comment]
> > > I've modified my post, should be valid now.
> 
> > 
> 
> > You still have cycles `Condition > AndCondition > Condition`
> 
> 
> 
> This is how I have it currently and the server returns the response nicely.

I can't say anything to that, it's still invalid GraphQL.

**Comment by budde377** [comment]
Thank you for reaching out and facilitating this discussion! I'm going to close the issue for now based on the arguments in https://github.com/heftapp/graphql_codegen/issues/92#issuecomment-1148602690. Furthermore, I think the fact that the generated code is based on invalid GraphQL elaborates the argument that this is not a very common use case, regardless of it working on your server.

I see a few possible solutions to your problem though:

* Manually create your classes and convert from the generated to the other classes.
* Create appropriate [extension methods](https://dart.dev/guides/language/extension-methods) or other utility methods to facilitate an easier conversion.
* Fork the project and implement your desired logic.

If I've misunderstood the underlying problem, please don't hesitate to reach out.

**Comment by szantogab** [comment]
Thank you, just a few points I'd like to add:

1. The graphql above may be invalid, but even if you don't want recursivity, you could still want the behaviour I described. 
2. All I really want is to be able to say in the build.yaml file that instead of `FragmentAndCondition$left`, please generate and use `FragmentCondition`. Do you think that'd involve too much development?

**Comment by szantogab** [comment]
Yes it'd be just a dumb replacement. Other codegens call this `replaceTypes` in their config files, so the user can just specify that instead of this class that the generator wants to generate, use this instead. As I see it, it's always good to have customizability and let the user decide how he wants to use the library.

I can create a proposal PR for this as soon as I have some more time on my hand.

**Comment by budde377** [comment]
After some thinking I believe I've found a solution. I would appreciate some feedback once it lands as `0.10.0-beta.1`
