### ISSUE TITLE
Add documentation for inline fragments

### ISSUE THREAD

**Issue by prolificcoder** [heftapp/graphql_codegen#95]
Looking at the readme there seems to be only support for fragments but when searching code base I can see references for InlineFragments https://graphql.org/learn/queries/#inline-fragments

Our query has them and I am not sure how to configure them. 

Can you please add some examples or documentation?

**Comment by budde377** [comment]
Sure, anything specific you're wondering about?

**Comment by prolificcoder** [comment]
The query I have is roughly of this format. 

````
query getPairs(id: Long){
account {
on AccountEntity {
...

}
````

Our schema has some unions, scalars and a lot of types. For backend folks the code generation was a breeze because of kotlin. It would be great if you can give a non-trivial schema as an example and how to configure the build.yaml for it.

**Comment by budde377** [comment]
Inline fragment spreads work just like fragment spreads with the exception that they don't generate any explicit `Fragment$YouFragment` classes. No special configuration is needed! 

So let's have the schema

```graphql

type Query {
  account: Account
}

union Account = 
  | PersonalAccount
  | BusinessAccount


type PersonalAccount {
  personName: String
}

type BusinessAccount {
  businessName: String
}
```

and the query 

```graphql

query FetchAccount {
  account {
    ... on PersonalAccount { personName }
    ... on BusinessAccount { businessName }
  } 
}
```

the generated classes will allow you to handle the data appropriately with code along the lines of


```dart

void printAccount(Query$FetchAccount$account account) {
  if (account is Query$FetchAccount$account$$PersonalAccount) print(account.personName);
  if (account is Query$FetchAccount$account$$BusinessAccount) print(account.businessName);
}

void printQuery(Query$FetchAccount query) {
  printAccount(query);  
}
```


This works but is a long class name! In these cases I usually opt to using named fragments

```graphql

fragment PersonalAccount on PersonalAccount { personName }

fragment BusinessAccount on BusinessAccount { businessName }

query FetchAccount { 
  account {
    ...BusinessAccount
    ...PersonalAccount
  }
}
```

which allows you to do the following

```dart

void printAccount(Query$FetchAccount$account account) {
  if (account is Fragment$PersonalAccount) print(account.personName);
  if (account is Fragment$BusinessAccount) print(account.businessName);
}

void printQuery(Query$FetchAccount query) {
  printAccount(query);  
}
```

**Comment by prolificcoder** [comment]
Thanks a lot @budde377 I was able to follow your instructions and do the code generation.
