### ISSUE TITLE
Reserved key in Graphql type breaks code generation

### ISSUE THREAD

**Issue by jhlabs** [heftapp/graphql_codegen#96]
I have experienced an edge case issue with this library while using it with the Graphql backend-as-a-service Hasura.

Hasura generates as part of other types the following input type:

```graphql
input jsonb_cast_exp {
  String: String_comparison_exp
}
```

The key `String` is very unfortunate naming. It breaks the code generation as it declares this name as a class member:

```dart
@JsonSerializable(explicitToJson: true, includeIfNull: false)
class Input$jsonb_cast_exp {
  Input$jsonb_cast_exp({this.String});

  @override
  factory Input$jsonb_cast_exp.fromJson(Map<String, dynamic> json) =>
      _$Input$jsonb_cast_expFromJson(json);

  final Input$String_comparison_exp? String;

  Map<String, dynamic> toJson() => _$Input$jsonb_cast_expToJson(this);
  int get hashCode {
    final l$String = String;
    return Object.hashAll([l$String]);
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (!(other is Input$jsonb_cast_exp) || runtimeType != other.runtimeType)
      return false;
    final l$String = String;
    final lOther$String = other.String;
    if (l$String != lOther$String) return false;
    return true;
  }
}
```
As `String` is not defined as a type, but as a member in the context of this class the compiler complains.

I am not sure if this issue is in the scope of this library, but would there be a way to solve this when one cannot change the type in the backend? In my case I have filed an issue with Hasura, but I am not sure they will make the changes.

**Comment by budde377** [comment]
You should [now](https://pub.dev/packages/graphql_codegen/versions/0.8.2-beta.3) be able to specify custom keywords in with the `extraKeywords` [option](https://github.com/heftapp/graphql_codegen/tree/main/packages/graphql_codegen#extra-keywords).

**Comment by jhlabs** [comment]
This fixed it perfectly and grateful for the fast turnaround as it was blocking our CI pipeline. Best maintained package ever 🤔?
